---
exhibitor: {
  version: latest, # 1.5.2, latest - https://github.com/Netflix/exhibitor/releases
  port:    8080,
  latest: {
    command: "curl -s '{{ common.repo.jcenter }}/com/netflix/exhibitor/exhibitor-standalone/' | grep '<pre>' | grep -v 'maven-metadata.xml' | sed -r 's/<[^>]+>//g' | tr -d '/' | tail -1",
    pattern: '^\d+\.\d+\.\d+$'
  },
  maven_repo:      '{{ common.repo.jcenter }}',
  gradle_provider: '{{ common.repo.github  }}/evgeny-goldin/gradle-provider.git',
  home:            /opt/exhibitor
}
