---
- name: Calculating Ansible version
  set_fact:
    ansible_version: "{{ ansible.version | calculate( ansible.latest ) }}"

- name: Installing Python pip
  apt:  name={{ item }} state=latest force=yes
  with_items:
    - python-pip
    - python-dev # Needed for installing Ansible in AWS Ubuntu AMI

- name: Installing Ansible
  pip:  name=ansible version={{ ansible_version }} extra_args="--upgrade"

- name: Creating Ansible inventory file
  file:
    path:  "{{ ansible.inventory_file | dirname }}"
    state: directory
- file:
    path:  "{{ ansible.inventory_file }}"
    state: touch
- lineinfile:
    dest:  "{{ ansible.inventory_file }}"
    line:  localhost

- include: "{{ common.utils.run }}"
  vars:
    title: Ansible checks
    commands:
      - { run: ansible --version,                   expect: "ansible {{ ansible_version }}" }
      - { run: ansible-playbook --version,          expect: "ansible-playbook {{ ansible_version }}" }
      - { run: ansible localhost -c local -m setup, expect: [ 'ansible_facts', 'ansible_date_time' ]}
