---
- apt:  name={{item}} state=latest
  with_items:
    - python-pip
    - python-dev

- pip:  name=ansible
  when: ( ansible.version == 'latest' )

- pip:  name=ansible version={{ ansible.version }}
  when: ( ansible.version != 'latest' )

- name: Create Ansible inventory file
  file:
    path:  "{{ ansible.inventory_file|dirname }}"
    state: directory
- file:
    path:  "{{ ansible.inventory_file }}"
    state: touch
- lineinfile:
    dest:  "{{ ansible.inventory_file }}"
    line:  localhost

- command:  ansible --version
  register: ansible_version

- command:  ansible-playbook --version
  register: ansible_playbook_version

- command:  ansible localhost -c local -m setup
  register: inventory

- assert:
    that:
      - ansible.version in ansible_version.stdout
      - ansible.version in ansible_playbook_version.stdout
  when: ansible.version != 'latest'

- assert:
    that:
      - "'ansible'          in ansible_version.stdout"
      - "'ansible-playbook' in ansible_playbook_version.stdout"
      - "'ansible_facts'    in inventory.stdout"
      - "'Ubuntu'           in inventory.stdout"
