---
- apt:  name={{item}} state=latest
  with_items:
    - python-pip
    - python-dev

- pip:  name=ansible
  when: ( ansible.version == 'latest' )

- pip:  name=ansible version={{ ansible.version }}
  when: ( ansible.version != 'latest' )

- command:  ansible --version
  register: ansible_version

- command:  ansible-playbook --version
  register: ansible_playbook_version

- assert:
    that:
      - ansible.version in ansible_version.stdout
      - ansible.version in ansible_playbook_version.stdout
  when: ansible.version != 'latest'

- assert:
    that:
      - "'ansible'          in ansible_version.stdout"
      - "'ansible-playbook' in ansible_playbook_version.stdout"
