---
ansible: {
  version: latest, # 1.9.0.1, latest - https://pypi.python.org/pypi/ansible
  latest: {
    command: "curl -Ls '{{ common.urls.pypi }}/ansible' | grep '<title>' | sed 's/^.*<title>//' | cut -d' ' -f2",
    pattern: '^\d+\.\d+(\.\d+)?(\.\d+)?$'
  },
  inventory_file: /etc/ansible/hosts
}
