---
- assert:
    that:
      - AWS_ACCOUNT_ID        is defined
      - AWS_ACCESS_KEY_ID     is defined
      - AWS_SECRET_ACCESS_KEY is defined

- group:
    name:  "{{ asgard.group }}"

- user:
    name:  "{{ asgard.user }}"
    group: "{{ asgard.group }}"
    home:  "{{ asgard.user_home }}"

- name: Create Asgard home dir
  file:
    path:  "{{ asgard.home }}"
    state: directory
    owner: "{{ asgard.user }}"
    group: "{{ asgard.group }}"
    mode:  0755

- name: Create Asgard log dir
  file:
    path:  "{{ asgard.log | dirname }}"
    state: directory
    owner: "{{ asgard.user }}"
    group: "{{ asgard.group }}"
    mode:  0755

- name: Create Asgard config
  template:
    src:   Config.groovy
    dest:  "{{ asgard.home }}"
    owner: "{{ asgard.user }}"
    group: "{{ asgard.group }}"

- name: Create Asgard init script
  template:
    src:  asgard
    dest: "{{ ubuntu.init_dir }}"
    owner: root
    group: root

- name: Chmod Asgard init script
  file:
    path:  "{{ ubuntu.init_dir }}/asgard"
    mode:  0755

# http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html
# http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
- name: Create AWS credentials directory
  file:
    path:  "{{ asgard.user_home }}/.aws"
    state: directory
    owner: "{{ asgard.user }}"
    group: "{{ asgard.group }}"
    mode:  0755

- name: Create AWS credentials file
  template:
    src:   credentials
    dest:  "{{ asgard.user_home }}/.aws"
    owner: "{{ asgard.user }}"
    group: "{{ asgard.group }}"
    mode:  0600

- name: Download Asgard JAR file
  get_url:
    url:  "{{ asgard.jar_url }}"
    dest: "{{ asgard.jar }}"

- name: Check Asgard java
  command: "{{ asgard.java }} -version"

- name: Restart Asgard service
  service: name=asgard state=restarted
