---
- set_fact:
    home:        "{{ ansible_env.HOME }}"

- set_fact:
    asgard_home: "{{ home }}/.asgard"
    asgard_jar:  "{{ home }}/asgard-standalone.jar"

- name: Create Asgard Home
  file:
    path:  "{{ asgard_home }}"
    state: directory
    mode:  0755

- name: Create Asgard config
  template:
    src:  roles/asgard/templates/Config.groovy
    dest: "{{ asgard_home }}"

- name: Create Asgard start script
  template:
    src:  roles/asgard/templates/asgard.sh
    dest: "{{ home }}"

- name: Chmod Asgard start script
  file:
    path:  "{{ home }}/asgard.sh"
    mode:  0755

- name: Download Asgard JAR file
  get_url:
    url:  "{{ asgard_jar_url }}"
    dest: "{{ asgard_jar }}"
