---
common: {
  mode: {
    directory: 0755,
    script:    0744,
    file:      0644,
    secret:    0600
  },

  net: {
    ports: {
      dns:    53,
      docker: 2375
    },
    localhost: localhost,
    local_ip:  127.0.0.1,
    any_ip:    0.0.0.0,
    # https://developers.google.com/speed/public-dns/
    public_dns: "8.8.8.8:53,8.8.4.4:53",
    ip_regex:   "(\\d+\\.){3}\\d+"
  },

  urls: {
    bintray:   'https://dl.bintray.com',
    docker:    'https://get.docker.com',
    github:    'https://github.com',
    golang:    'https://golang.org',
    gradle:    'https://gradle.org',
    jcenter:   'https://jcenter.bintray.com',
    jfrog:     'https://repo.jfrog.org',
    pypi:      'https://pypi.python.org/pypi',
    ruby:      'https://www.ruby-lang.org',
    tomcat:    'https://tomcat.apache.org',
    jenkins:   'https://updates.jenkins-ci.org',
    jetbrains: 'https://www.jetbrains.com'
  },

  utils: {
    download: "{{ playbook_dir }}/utils/download.yml",
    fake:     "{{ playbook_dir }}/utils/fake.yml",
    include:  "{{ playbook_dir }}/utils/include.yml",
    register: "{{ playbook_dir }}/utils/register.yml",
    run:      "{{ playbook_dir }}/utils/run.yml",
    service:  "{{ playbook_dir }}/utils/service.yml",
    verify:   "{{ playbook_dir }}/utils/verify.yml"
  },

  roles: {
    tomcat:    "{{ playbook_dir }}/roles/tomcat/tasks/main.yml",
    exhibitor: "{{ playbook_dir }}/roles/exhibitor/tasks/main.yml",
    gradle:    "{{ playbook_dir }}/roles/gradle/tasks/main.yml",
    register:  "{{ playbook_dir }}/roles/skydns/register-host.yml",
    gatling:   "{{ playbook_dir }}/roles/gatling/run-simulations.yml"
  }
}
