---
common: {
  mode: {
    directory: 0755,
    script:    0744,
    file:      0644,
    secret:    0600
  },

  net: {
    dns_port:  53,
    localhost: 127.0.0.1,
    any_ip:    0.0.0.0,
    # https://developers.google.com/speed/public-dns/
    public_dns: "8.8.8.8:53,8.8.4.4:53",
  },

  github:  'https://github.com',
  jcenter: 'https://jcenter.bintray.com',
  bintray: 'https://dl.bintray.com',

  download_unpack: "{{ playbook_dir }}/roles/download-unpack.yml",
  mkdir:           "{{ playbook_dir }}/roles/mkdir.yml",

  # Whether roles should start services installed
  start_service: true
}
