---
common: {
  mode: {
    directory: 0755,
    script:    0744,
    file:      0644,
    secret:    0600
  },

  net: {
    dns_port:  53,
    localhost: 127.0.0.1,
    any_ip:    0.0.0.0,
    # https://developers.google.com/speed/public-dns/
    public_dns: "8.8.8.8:53,8.8.4.4:53",
  },

  repo: {
    github:   'https://github.com',
    jcenter:  'https://jcenter.bintray.com',
    bintray:  'https://dl.bintray.com',
    jfrog:    'https://repo.jfrog.org'
  },

  utils: {
    download: "{{ playbook_dir }}/utils/download.yml",
    mkdir:    "{{ playbook_dir }}/utils/mkdir.yml",
    service:  "{{ playbook_dir }}/utils/service.yml",
    verify:   "{{ playbook_dir }}/utils/verify.yml"
  },

  roles: {
    tomcat:   "{{ playbook_dir }}/roles/tomcat/tasks/main.yml",
    register: "{{ playbook_dir }}/roles/skydns/register-host.yml"
  }
}
