---
- set_fact:
    registrar_plugin: "{{ helios.agent.registrar_plugin.archive | tokens( helios.agent.registrar_plugin ) }}"
    agent_name:       "{{ ansible_hostname }}.{{ domain }}"

- include: verify-master.yml master={{ helios_master }} host="{{ agent_name }}"
- include: verify-helios.yml

- debug: msg="De-registering Helios agent '{{ agent_name }}'"
- command: "{{ helios_command }} deregister --yes '{{ agent_name }}'"
  ignore_errors: yes

- name: Stopping Helios agent service
  service: name=helios-agent state=stopped
  ignore_errors: yes

- file: path={{ helios.agent.config_endpoints | dirname }} state=directory

- include: "{{ common.utils.download }}"
  vars:
    title:   Helios registrar plugin
    url:     "{{ helios.agent.registrar_plugin.url     | tokens( helios.agent.registrar_plugin ) }}"
    archive: "{{ registrar_plugin }}"
    configs:
      - { role: helios, from: agent-config,           to: "{{ helios.agent.config }}" }
      - { role: helios, from: agent-config-endpoints, to: "{{ helios.agent.config_endpoints }}" }

- name: Installing Helios agent
  apt:  deb="{{ helios.home }}/helios-agent_{{ helios_version }}_all.deb"

- name:  Updating Helios agent script
  shell: sed -i "s|exec java|exec '{{ java_home }}/bin/java'|" '{{ helios.agent.script }}'

- include: agent-docker.yml

- name:    Starting Helios agent service
  service: name=helios-agent state=started enabled=yes

- pause:   seconds=5
- include: verify-helios.yml agent={{ agent_name }}
