---
# --------------------------------------------
#   Common tasks for Helios master and agent
# --------------------------------------------
- include: check-vars.yml
  when: helios_master is defined

- include: "{{ common.utils.fake }}"
  vars:
    # We have Java 8 JRE installed already
    package: java7-runtime

- name: Calculating Helios version
  set_fact:
    helios_version:     "{{ helios.version     | calculate( helios.latest ) }}"
    helios_master_port: "{{ helios_master_port | default( helios.master.port ) }}"

- include: "{{ common.utils.download }}"
  vars:
    title:   Helios
    url:     "{{ helios.url     | tokens({ 'version': helios_version }) }}"
    archive: "{{ helios.archive | tokens({ 'version': helios_version }) }}"
    home:    "{{ helios.home }}"

- name: Installing Helios packages
  apt:  deb="{{ helios.home }}/helios-services_{{ helios_version }}_all.deb"
  when: helios_master is defined

- apt:  deb="{{ helios.home }}/helios_{{ helios_version }}_all.deb"

- include: "{{ common.utils.run }}"
  vars:
    title:   Helios checks
    commands:
      - { run: helios --version, expect: 'Spotify Helios CLI {{ helios_version }}'  }

- name: Installing Python pip
  apt:  name=python-pip state=latest force=yes
  when: helios_master is defined

- name: Installing zk-shell
  pip:  name=zk-shell state=latest
  when: helios_master is defined
