---
# --------------------------------------------
#   Common tasks for Helios master and agent
# --------------------------------------------
- name: Setting up Helios variables
  set_fact: helios_version="{{ helios.version | calculate( helios.latest ) }}"

- name: Installing JDK
  apt: name=default-jdk state=latest force=yes

- name:     Running Java
  shell:    java -version 2>&1
  register: java_out

- name:  Verifying Java
  assert:
    that:
      - "'OpenJDK Runtime Environment' in java_out.stdout"
      - "'OpenJDK 64-Bit Server VM'    in java_out.stdout"

- include: "{{ playbook_dir }}/roles/download-unpack.yml"
  vars:
    name:    Helios
    url:     "{{ helios.url     | tokens( { 'version': helios_version } ) }}"
    archive: "{{ helios.archive | tokens( { 'version': helios_version } ) }}"
    home:    "{{ helios.home }}"

- name: Installing Helios services
  apt:  deb="{{ helios.home }}/helios-services_{{ helios_version }}_all.deb"
