---
# ----------------------------------------------
# Common tasks between Helios master and agent
# ----------------------------------------------
- name: Setting up Helios variables
  set_fact: helios_version="{{ helios.version | calculate( helios.latest ) }}"
- name: Setting up Helios variables
  set_fact: helios_archive=/opt/helios-{{ helios_version }}.tar.gz

- name: Installing packages
  apt: name={{ item }}
  with_items:
    - default-jdk
    - golang

- name:     Running Go
  shell:    go version 2>&1
  register: go_out

- name:     Running Java
  shell:    java -version 2>&1
  register: java_out

- name:  Verifying Go
  assert:
    that:
      - "'go version' in go_out.stdout"
      - "'linux'      in go_out.stdout"

- name:  Verifying Java
  assert:
    that:
      - "'OpenJDK Runtime Environment' in java_out.stdout"
      - "'OpenJDK 64-Bit Server VM'    in java_out.stdout"

- name: Downloading Helios packages archive
  get_url:
    url:  '{{ helios.download_url }}/{{ helios_version }}/helios-debs.tar.gz'
    dest: "{{ helios_archive }}"

- file: path={{ helios.packages }} state=absent
- file: path={{ helios.packages }} state=directory

- name: Unpacking Helios packages archive
  unarchive:
    src:  "{{ helios_archive }}"
    dest: "{{ helios.packages }}"
    copy: false

- name: Installing Helios services
  apt:  deb="{{ helios.packages }}/helios-services_{{ helios_version }}_all.deb"
