---
# ----------------------------------------------
# Common tasks between Helios master and agent
# ----------------------------------------------
- name: Setting up Helios variables
  set_fact: helios_version="{{ helios.version | calculate( helios.latest ) }}"
  
- name: Installing packages
  apt: name={{ item }}
  with_items:
    - default-jdk
    - golang

- name:     Running Go
  shell:    go version 2>&1
  register: go_out

- name:     Running Java
  shell:    java -version 2>&1
  register: java_out

- name:  Verifying Go
  assert:
    that:
      - "'go version' in go_out.stdout"
      - "'linux'      in go_out.stdout"

- name:  Verifying Java
  assert:
    that:
      - "'OpenJDK Runtime Environment' in java_out.stdout"
      - "'OpenJDK 64-Bit Server VM'    in java_out.stdout"

- name: Downloading Helios packages archive
  get_url:
    url:  "{{ helios.url     | tokens( { 'version': helios_version } ) }}"
    dest: "{{ helios.archive | tokens( { 'version': helios_version } ) }}"

- file: path={{ helios.home }} state=absent
- file: path={{ helios.home }} state=directory

- name: Unpacking Helios packages archive
  unarchive:
    src:  "{{ helios.archive | tokens( { 'version': helios_version } ) }}"
    dest: "{{ helios.home }}"
    copy: false

- name: Installing Helios services
  apt:  deb="{{ helios.home }}/helios-services_{{ helios_version }}_all.deb"
