---
# --------------------------------------------
#   Common tasks for Helios master and agent
# --------------------------------------------
- debug: var=helios_master
- debug: var=helios_master_port
- debug: var=zookeeper_port
- debug: var=etcd_port
- debug: var=exhibitor_port
- debug: var=domain
- debug: var=ansible_fqdn
- debug: var=facter_ipaddress_eth1

- set_fact:
    helios_version:     "{{ helios.version     | calculate( helios.latest ) }}"
    helios_master_port: "{{ helios_master_port | default( helios.master.port ) }}"

- include: "{{ common.path.download_unpack }}"
  vars:
    name:    Helios
    url:     "{{ helios.url     | tokens({ 'version': helios_version }) }}"
    archive: "{{ helios.archive | tokens({ 'version': helios_version }) }}"
    home:    "{{ helios.home }}"

- name: Installing Helios services
  apt:  deb="{{ helios.home }}/helios-services_{{ helios_version }}_all.deb"
