---
# ----------------------------------------------
# Common tasks between Helios master and agent
# ----------------------------------------------

- name: Installing Java
  apt: name=default-jdk

- name:     Running Java
  shell:    java -version 2>&1
  register: java_out

- name:  Verifying Java
  assert:
    that:
      - "'OpenJDK Runtime Environment' in java_out.stdout"
      - "'OpenJDK 64-Bit Server VM'    in java_out.stdout"

- name: Setting up Helios common variables
  set_fact:
    helios_archive: /opt/helios-{{ helios_version }}.tar.gz

- name: Downloading Helios packages archive
  get_url:
    url:  '{{ helios.download_url }}/{{ helios_version }}/helios-debs.tar.gz'
    dest: "{{ helios_archive }}"

- file: path={{ helios.helios_packages }} state=absent
- file: path={{ helios.helios_packages }} state=directory

- name: Unpacking Helios packages archive
  unarchive:
    src:  "{{ helios_archive }}"
    dest: "{{ helios.helios_packages }}"
    copy: false

- name: Installing Helios services
  apt:  deb="{{ helios.helios_packages }}/helios-services_{{ helios_version }}_all.deb"
