---
- set_fact:
    master_name: "{{ ansible_hostname }}.{{ domain }}"

- name: Stopping Helios master service
  service: name=helios-master state=stopped
  ignore_errors: yes

- name: Copying Helios master config
  template:
    src:  master-config
    dest: "{{ helios.master.config }}"

- name: Installing Helios master
  apt:  deb="{{ helios.home }}/helios-master_{{ helios_version }}_all.deb"

- name:  Updating Helios master script
  shell: sed -i "s|exec java|exec '{{ java_home }}/bin/java'|" '{{ helios.master.script }}'

- name: Starting Helios master service
  service: name=helios-master state=started enabled=yes

- include: verify-master.yml master={{ common.net.localhost }} host="{{ master_name }}"
- include: verify-master.yml master={{ helios_master }} host="{{ master_name }}"
- include: verify-helios.yml
