---
# -------------------------------------------------------------
# https://github.com/spotify/helios
# -------------------------------------------------------------

- name: Setting up variables
  set_fact:
    helios_version:    "{{ helios.version | calculate( helios.latest ) }}"
    exhibitor_version: "{{ helios.exhibitor.version | calculate( helios.exhibitor.latest ) }}"
    helios_packages:   /opt/helios
    exhibitor_home:    /opt/exhibitor

- include: zookeeper.yml
- include: exhibitor.yml
- include: helios-master.yml
