---
# ---------------------------------------------------------------
#    Verifies connectivity with Helios master and its services
# ---------------------------------------------------------------
- debug: msg="Verifying Helios master '{{ master }}' endpoints (will register '{{ register_host }}')"

- include: "{{ common.utils.verify }}"
  vars:
    title: Helios master DNS and ZooKepper
    host:  "{{ master }}"
    ports:
      - "{{ common.net.ports.dns }}"
      - "{{ zookeeper_port }}"

- include: "{{ common.utils.run }}"
  vars:
    title: "'_helios._http.{{ domain }}' SRV test"
    commands:
      - { run:    "dig '@{{ master }}' '{{ helios.srv_prefix }}.{{ domain }}' SRV",
          expect: '^{{ helios.srv_prefix }}\.{{ domain }}\.\s+\d+\s+IN\s+SRV\s+\d+\s+\d+\s+{{ helios_master_port }}\s+.+\.{{ domain }}\.$' }
      - { run:    "host -t SRV '{{ helios.srv_prefix }}.{{ domain }}' '{{ master }}'",
          expect: '^{{ helios.srv_prefix }}.{{ domain }} has SRV record \d+ \d+ {{ helios_master_port }} .+\.{{ domain }}.$' }

- include: "{{ common.utils.verify }}"
  vars:
    title: Helios master service
    host:  "{{ master }}"
    port:  "{{ helios_master_port }}"
    verify:
      - { status: 404 }

- include: "{{ common.utils.verify }}"
  vars:
    title: Helios master etcd
    host:  "{{ master }}"
    port:  "{{ etcd_port }}"
    verify:
      - { path: /version,         content: '"releaseVersion":' }
      - { path: /v2/stats/leader, content: '{"leader":"' }

- include: "{{ common.utils.run }}"
  vars:
    title: ZooKeeper check
    commands:
      - { run:    "echo 'ls /' | zk-shell '{{ master }}:{{ zookeeper_port }}' --run-from-stdin",
          expect: zookeeper  }

#                         VirtualBox                              AWS
- set_fact: my_ip="{{ facter_ipaddress_eth1 | default( ansible_default_ipv4.address )}}"
- debug:    msg="My IP is [{{ my_ip }}]"

- include: "{{ common.utils.register }}"
  vars:
    etcd_host: "{{ master }}"
    src:       "{{ register_host }}"
    dest:      "{{ my_ip }}"
