---
# ------------------------------------------------------------------------
#    Verifies Helios functionality by deploying test Nginx container
# ------------------------------------------------------------------------
- set_fact: create_nginx_job="create '{{ helios.docker.nginx.job }}' '{{ helios.docker.nginx.image }}' -p http=80:{{ helios.docker.nginx.port }} --register nginx || echo 'Done.'"
- debug: var=create_nginx_job

- debug: msg="Verifying Helios master '{{ helios_command }}'"
  when:  agent is not defined

- debug: msg="Verifying Helios master '{{ helios_command }}' and agent '{{ agent }}'"
  when:  agent is defined

- include: "{{ common.utils.run }}"
  vars:
    title: Helios master '{{ helios_command }}' status checks
    commands:
      - { run:    '{{ helios_command }} jobs',
          expect: [ JOB ID, NAME, VERSION, HOSTS, COMMAND, ENVIRONMENT ]}
      - { run:    '{{ helios_command }} hosts',
          expect: [ HOST, STATUS, DEPLOYED, RUNNING, CPUS, MEM, LOAD AVG, MEM USAGE, OS, HELIOS, DOCKER ]}
      - { run:    '{{ helios_command }} {{ create_nginx_job }}',
          expect: [ 'Creating job:', '"id":"{{ helios.docker.nginx.job }}:', 'Done.' ]}
      - { run:    '{{ helios_command }} inspect "{{ helios.docker.nginx.job }}"',
          expect: 'Image: nginx' }
      - { run:    '{{ helios_command }} jobs',
          expect: '{{ helios.docker.nginx.job }}:' }

- include: "{{ common.utils.run }}"
  vars:
    title: Helios agent '{{ agent }}' - Docker
    commands:
      - { run:    '{{ helios_command }} hosts',
          expect: '{{ agent }}.    Up ' }
      - { run:    '{{ helios_command }} undeploy --yes "{{ helios.docker.nginx.job }}" "{{ agent }}" || echo "{{ agent }}: done"',
          expect: [ 'Undeploying {{ helios.docker.nginx.job }}:', '{{ agent }}: done' ]}
      - { run:    '{{ helios_command }} deploy "{{ helios.docker.nginx.job }}" "{{ agent }}"',
          expect: [ 'Deploying Deployment{jobId={{ helios.docker.nginx.job }}:', 'on [{{ agent }}]', '{{ agent }}: done' ]}
      - { run:    sleep 15 }
      - { run:    '{{ helios_command }} status --job "{{ helios.docker.nginx.job }}"',
          expect: [ '{{ helios.docker.nginx.job }}', '{{ agent }}.    START    RUNNING' ]}
      - { run:    '{{ helios_command }} status --host "{{ agent }}"',
          expect: [ '{{ helios.docker.nginx.job }}', '{{ agent }}.    START    RUNNING' ]}
      - { run:    docker ps,
          expect: [ 'nginx', 'seconds ago', ' Up ', '443/tcp, {{ common.net.any_ip }}:{{ helios.docker.nginx.port }}->80/tcp' ]}
      - { run:    'curl -s http://localhost:{{ helios.docker.nginx.port }}',
          expect: [ 'Welcome to nginx!', 'Thank you for using nginx.' ]}
  when: agent is defined

- set_fact:
    nginx_srv_service: "nginx.http.{{ domain }}"
    nginx_srv_host:    "{{ agent }}"
  when: agent is defined and ( not ( use_consul|bool ))

- set_fact:
    nginx_srv_service: "nginx.service.{{ domain }}"
    nginx_srv_host:    "{{ ansible_hostname }}.node.dc1.{{ domain }}"
  when: agent is defined and use_consul|bool

- include: "{{ common.utils.run }}"
  vars:
    title: Helios agent '{{ agent }}' - SRV
    commands:
      - { run:    "dig '@{{ master }}' '{{ nginx_srv_service }}' SRV",
          expect: '^{{ nginx_srv_service }}\.\s+\d+\s+IN\s+SRV\s+\d+\s+\d+\s+{{ helios.docker.nginx.port }}\s+{{ nginx_srv_host }}.$' }
      - { run:    "host -t SRV '{{ nginx_srv_service }}' '{{ master }}'",
          expect: '^{{ nginx_srv_service }} has SRV record \d+ \d+ {{ helios.docker.nginx.port }} {{ nginx_srv_host }}.$' }
  when: agent is defined
