---
# ---------------------------------------------------------
#   Verifies connectivity with Helios master and services
# ---------------------------------------------------------
- debug: msg="Verifying Helios master '{{ master }}' endpoints"

- include: "{{ common.utils.verify }}"
  vars:
    title: Helios master DNS and ZooKepper
    host:  "{{ master }}"
    ports:
      - "{{ common.net.dns_port }}"
      - "{{ zookeeper_port }}"

- include: "{{ common.utils.verify }}"
  vars:
    title: Helios master service
    host:  "{{ master }}"
    port:  "{{ helios_master_port }}"
    verify:
      - { status: 404 }

- include: "{{ common.utils.verify }}"
  vars:
    title: Helios master etcd
    host:  "{{ master }}"
    port:  "{{ etcd_port }}"
    verify:
      - { path: /version, content: '"releaseVersion":' }
      - { path: /v2/keys, content: '{"action":"get"'   }

- include: "{{ common.utils.verify }}"
  vars:
    title: Helios master Exhibitor
    host:  "{{ master }}"
    port:  "{{ exhibitor_port }}"
    verify:
      - { path: /exhibitor/v1/ui/index.html, content: Exhibitor for ZooKeeper }

- include: "{{ common.roles.register }}"
  vars:
    etcd_host:   "{{ master }}"
    skydns_host: "{{ master }}"
    fqdn:        "{{ ansible_fqdn }}"
    ip:          "{{ facter_ipaddress_eth1 }}"
