---
- name: Calculating Vagrant version
  set_fact:
    vagrant_version: "{{ vagrant.version | calculate( vagrant.latest ) }}"

- include: "{{ common.utils.download }}"
  vars:
    title:   Vagrant
    url:     "{{ vagrant.url     | tokens({ 'version': vagrant_version })}}"
    archive: "{{ vagrant.archive | tokens({ 'version': vagrant_version })}}"
    tests:
      - { run: vagrant --version, expect: "Vagrant {{ vagrant_version }}" }
