---
- name: Calculating Artifactory version
  set_fact:
    artifactory_version: "{{ artifactory.version | calculate( artifactory.latest ) }}"
- set_fact:
    artifactory_port:    "{{ port         | default( artifactory.port ) }}"
    java_options:        "{{ java_options | default( '' ) }}"

- debug: msg="Running Artifactory on port {{ artifactory_port }}, Java options '{{ java_options }}'"

- name:    Stopping and disabling Nexus service, if found
  service: name=nexus state=stopped enabled=no
  ignore_errors: yes

- include: standalone.yml
  when:    artifactory.run == 'standalone'

- include: war.yml
  when:    artifactory.run == 'war'

- include: mysql.yml
  when:    artifactory.mysql.enabled|bool

- include: import.yml
  when:    import is defined
