---
- name: Calculating Artifactory version
  set_fact:
    artifactory_version: "{{ artifactory.version | calculate( artifactory.latest ) }}"
- set_fact:
    artifactory_port:    "{{ artifactory_port    | default( artifactory.port ) }}"
    artifactory_home:    "{{ artifactory.home }}/artifactory-{{ artifactory_version }}"

- include: "{{ common.utils.service }}"
  vars:
    name:        Artifactory
    service:     artifactory
    url:         "{{ artifactory.url     | tokens({ 'version': artifactory_version }) }}"
    archive:     "{{ artifactory.archive | tokens({ 'version': artifactory_version }) }}"
    home:        "{{ artifactory.home }}"
    config_src:  "{{ playbook_dir }}/roles/artifactory/templates/server.xml"
    config_dest: "{{ artifactory_home }}/tomcat/conf/server.xml"
    command:     "{{ artifactory_home }}/bin/artifactory.sh"
    port:        "{{ artifactory_port }}"
    status:      200
    content:     '0;URL=/artifactory'

- name:     Waiting for Artifactory to start
  command:  curl 'http://{{ common.net.localhost }}:{{ artifactory_port }}/artifactory/api/system/ping'
  register: ping_result
  until:    ping_result.stdout == 'OK'
  retries:  20
  delay:    3

- name: Verifying Artifactory HTTP endpoints
  uri:  url="http://{{ common.net.localhost }}:{{ artifactory_port }}{{ item.path }}"
  with_items:
    - { path: "/artifactory/api/system/ping" }
    - { path: "/artifactory/api/application.wadl" }
    - { path: "/artifactory/api/search/artifact?name=name" }
    - { path: "/artifactory/webapp/home.html" }
    - { path: "/artifactory/webapp/browserepo.html" }
