---
- name: Calculating Artifactory version
  set_fact:
    artifactory_version: "{{ artifactory.version | calculate( artifactory.latest ) }}"
- set_fact:
    artifactory_port:    "{{ artifactory_port    | default( artifactory.port ) }}"
    java_options:        "{{ java_options        | default( '' ) }}"

- include: standalone.yml
  when:    artifactory.run == 'standalone'

- include: war.yml
  when:    artifactory.run == 'war'

- include: import.yml
  when:    import is defined
