---
# -----------------------------------------------------------
# https://www.jfrog.com/confluence/display/RTF20/Dedicated+Tomcat+Instance
# -----------------------------------------------------------
- include: "{{ common.roles.tomcat }}"
  vars:
    tomcat_port:   "{{ artifactory_port }}"
    catalina_opts: "{{ artifactory.war.java_options }} {{ java_options }}"

- set_fact:
    artifactory_home: "{{ artifactory.war.home }}"
    artifactory_lib:  "{{ tomcat_home }}/lib"

- include: "{{ common.utils.service }}"
  vars:
    title:   Artifactory
    service: artifactory
    url:     "{{ artifactory.war.url     | tokens({ 'version': artifactory_version }) }}"
    archive: "{{ artifactory.war.archive | tokens({ 'version': artifactory_version }) }}"
    home:    "{{ tomcat_webapps }}/artifactory"
    command: "{{ tomcat_run }}"
    env:
      ARTIFACTORY_HOME: "{{ artifactory_home }}"
    start_service: "{{ not ( artifactory.mysql.enabled | bool ) }}"
    port:    "{{ artifactory_port }}"
    timeout: "{{ artifactory.timeout }}"
    wait:    "{{ artifactory.wait }}"
    verify:  "{{ artifactory.verify }}"
