---
- include: "{{ common.roles.tomcat }}"
  vars:
    tomcat_port:   "{{ artifactory_port }}"
    catalina_opts: "{{ artifactory.war.java_options }} {{ java_options }}"

- include: "{{ common.utils.service }}"
  vars:
    service: artifactory
    title:   Artifactory
    url:     "{{ artifactory.war.url     | tokens({ 'version': artifactory_version }) }}"
    archive: "{{ artifactory.war.archive | tokens({ 'version': artifactory_version }) }}"
    home:    "{{ tomcat_webapps }}/artifactory"
    command: "{{ tomcat_run }}"
    port:    "{{ artifactory_port }}"
    timeout: "{{ artifactory.timeout }}"
    wait:    "{{ artifactory.wait }}"
    verify:  "{{ artifactory.verify }}"
