---
# http://docs.docker.com/installation/ubuntulinux/

- name:    Adding Docker repository key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name:           Adding Docker repository
  apt_repository: repo='deb {{ common.urls.docker }}/ubuntu docker main' update_cache=yes

- name: Installing Docker
  apt:  name=lxc-docker state=latest force=yes

- name:     Running Docker version
  command:  docker --version
  register: docker_version_out
- assert:
    that:
      - "'Docker version' in docker_version_out.stdout"

- command: "{{ item }}"
  with_items:
    - docker ps
    - docker images

- command:    "docker pull '{{ item }}'"
  with_items: pull
  when: pull is defined

- shell:    docker images | grep -v 'IMAGE ID' | awk '{print $1}' | sort -u
  register: docker_images

- debug: var=docker_images.stdout_lines

- fail: msg="Image '{{ item }}' is not found in the list of images pulled - {{ docker_images.stdout_lines }}"
  when: item not in docker_images.stdout_lines
  with_items: pull | default([])

- include: start.yml
  when: start is defined
