---
# http://docs.docker.com/installation/ubuntulinux/

- name:    Adding Docker repository key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name:           Adding Docker repository
  apt_repository: repo='deb {{ common.urls.docker }}/ubuntu docker main' update_cache=yes

- name: Installing Docker
  apt:  name=lxc-docker state=latest force=yes

- name:     Running Docker version
  command:  docker --version
  register: docker_version_out
- assert:
    that:
      - "'Docker version' in docker_version_out.stdout"

- command: "{{ item }}"
  with_items:
    - docker ps
    - docker images

- command:    "docker pull '{{ item }}'"
  with_items: images
  when: images is defined

- include: auto-start.yml
  when:    auto_start is defined
  vars:
    image: "{{ auto_start }}"
