---
consul: {
  version: latest, # 0.5.0, latest - https://www.consul.io/downloads.html
  ports: {
    http:   8500,
    dns:    8600,
    gossip: 8301
  },
  latest: {
    command: "curl -Ls 'https://www.consul.io/downloads.html' | grep '{{ common.urls.bintray }}/mitchellh/consul/' | grep 'linux_amd64' | cut -d'/' -f6 | cut -d'_' -f1",
    pattern: '^\d+\.\d+\.\d+$'
  },
  url:      '{{ common.urls.bintray }}/mitchellh/consul/<version>_linux_amd64.zip',
  archive:  /opt/consul-<version>.zip,
  home:     /opt/consul,
  data_dir: /opt/consul/data,
  verify: [
    { path: /,                          content: Consul Agent },
    { path: /v1/agent/service/register, content: Request decode failed, status: 400 },
    { path: /v1/catalog/service,        content: Missing service name,  status: 400 }
  ]
}

consul_env: {
  PATH: "$PATH:{{ consul.home }}"
}
