---
- set_fact:
    etcd_dir: "{{ etcd.dir_name | tokens( etcd ) }}"
- set_fact:
    etcd_bin: "{{ etcd.home }}/{{ etcd_dir }}/etcd"

- include: "{{ common.utils.service }}"
  vars:
    service:     etcd
    title:       etcd
    url:         "{{ etcd.url     | tokens({ 'dir_name': etcd_dir, 'version': etcd.version }) }}"
    archive:     "{{ etcd.archive | tokens( etcd ) }}"
    home:        "{{ etcd.home }}"
    configs:
      - { from: "{{ playbook_dir }}/roles/skydns/templates/etcd-config", to: "{{ etcd.config }}" }
    env_config:  "{{ etcd.config }}"
    test:        { run: "{{ etcd_bin }} --version", expect: "{{ etcd.version }}" }
    command:     "{{ etcd_bin }} $ETCD_OPTS"
    port:        "{{ etcd_port | default( etcd.port ) }}"
    path:        '/version'
    content:     "{{ etcd.version }}"
