---
- debug: msg="Setting up SkyDNS name server for domain '{{ domain }}'"
- set_fact:
    skydns_bin: "{{ skydns.home }}/skydns"

- include: "{{ common.utils.service }}"
  vars:
    service: skydns
    title:   SkyDNS
    url:     "{{ skydns.url }}"
    archive: "{{ skydns.archive }}"
    home:    "{{ skydns.home }}"
    env:
      # https://github.com/skynetservices/skydns
      PATH:               "$PATH:{{ skydns.home }}"
      SKYDNS_DOMAIN:      "{{ domain }}"
      SKYDNS_ADDR:        "{{ common.net.any_ip }}:{{ common.net.ports.dns }}"
      ETCD_MACHINES:      "{{ common.net.local_ip }}:{{ etcd_port }}"
      SKYDNS_NAMESERVERS: "{{ common.net.public_dns }}"
    tests:
      - { run: "'{{ skydns_bin }}' --help", expect: 'Usage of {{ skydns_bin }}:' }
      - { run: "skydns --help",             expect: 'Usage of skydns:' }
    # Waiting a bit while etcd service is starting
    depends: etcd
    command: "sleep 5 && '{{ skydns_bin }}' $SKYDNS_OPTS"
    ports:
      - "{{ etcd_port }}"
      - "{{ common.net.ports.dns }}"
    verify:
      - { path: /version,         content: '"releaseVersion":"{{ etcd.version }}"' }
      - { path: /v2/stats/leader, content: '{"leader":"' }

- include: "{{ common.utils.run }}"
  vars:
    title: local dig
    commands:
      - { run: "dig @{{ common.net.localhost }}", expect: [ Got answer, QUESTION SECTION, 'SERVER: {{ common.net.local_ip }}#{{ common.net.ports.dns }}({{ common.net.local_ip }})' ]}
      - { run: "dig @{{ common.net.local_ip }}",  expect: [ Got answer, QUESTION SECTION, 'SERVER: {{ common.net.local_ip }}#{{ common.net.ports.dns }}({{ common.net.local_ip }})' ]}
