---
- debug: var=skydns_domain

- set_fact:
    skydns_root: "{{ golang.home }}/src/{{ skydns.url }}"
- set_fact:
    skydns_bin:  "{{ skydns_root }}/skydns"

- name:        Downloading SkyDNS
  command:     go get '{{ skydns.url }}'
  environment: "{{ golang_env | expand_path }}"

- name: Switching SkyDNS tag
  command: git checkout '{{ skydns.version }}'
  args:
    chdir: "{{ skydns_root }}"

- name: Building SkyDNS
  command: go build -v
  args:
    chdir: "{{ skydns_root }}"
  environment: "{{ golang_env | expand_path }}"

- include: "{{ common.utils.service }}"
  vars:
    service:    skydns
    title:      SkyDNS
    configs:
      - { from: config, to: "{{ skydns.config }}" }
    env_config: "{{ skydns.config }}"
    command:    "{{ skydns_bin }} $SKYDNS_OPTS"
    port:       "{{ common.net.dns_port }}"

- name:     Running local dig
  command:  dig @{{ common.net.localhost }}
  register: dig_out

- name: Verifying local dig
  assert:
    that:
      - "'Got answer'       in dig_out.stdout"
      - "'QUESTION SECTION' in dig_out.stdout"
      - "'SERVER: {{ common.net.localhost }}#{{ common.net.dns_port }}({{ common.net.localhost }})' in dig_out.stdout"
