---
nexus: {
  version: '2.11.2-03', # http://www.sonatype.org/nexus/thank-you-for-downloading/?dl=tgz
  port:    8080,
  timeout: 120,         # in seconds
  run:     standalone,  # standalone, war
  standalone: {
    url:     'https://sonatype-download.global.ssl.fastly.net/nexus/oss/nexus-<version>-bundle.tar.gz',
    archive: /opt/nexus-<version>.tar.gz,
    home:    /opt/nexus
  },
  war: {
    url:          '{{ common.urls.jcenter }}/org/sonatype/nexus/nexus-webapp/<version>/nexus-webapp-<version>.war',
    archive:      /opt/nexus-<version>.war,
    java_options: '-Xms256m -Xmx768m -XX:MaxPermSize=192m -Djava.io.tmpdir=./tmp -Djava.net.preferIPv4Stack=true'
  },
  wait: [
    { path: /nexus, content: nexusVersion= }
  ],
  verify: [
    { path: /nexus, content: Sonatype Nexus },
    { path: /nexus, content: Loading Nexus UI },
    { path: /nexus/service/local/attributes, status: 401 }
  ],
  auth: {
    user: admin,
    pass: admin123
  },
  import: {
    archive: /opt/repo-import.<ext>,
    home:    <home>/sonatype-work/nexus/storage,
    repo:    releases
  },
  # https://repository.sonatype.org/nexus-indexer-lucene-plugin/default/docs/path__lucene_search.html
  # https://support.sonatype.com/entries/22189106-How-can-I-programatically-upload-an-artifact-into-Nexus-
  # http://stackoverflow.com/a/19699401/472153
  path: {
    artifact:     /nexus/content/repositories/<repo>/<artifact>,
    upload: {
      path:       '/nexus/service/local/artifact/maven/content?r=releases&g=<g>&a=<a>&v=<v>',
      method:     POST,
      headers:    []
    },
    search: {
      quick:      '/nexus/service/local/lucene/search?q=<name>&count=10000000',
      groupId:    '/nexus/service/local/lucene/search?g=<g>&count=10000000',
      artifactId: '/nexus/service/local/lucene/search?a=<a>&count=10000000',
      version:    '/nexus/service/local/lucene/search?v=<v>&count=10000000',
      gav:        '/nexus/service/local/lucene/search?g=<g>&a=<a>&v=<v>&count=10000000'
    }
  }
}
