---
- name: Calculating Ruby version
  set_fact:
    ruby_version: "{{ ruby.version | calculate( ruby ) }}"

- set_fact:
    rvm_sh:   /opt/rvm.sh
    ruby_bin: "{{ ruby.rvm.home }}/rubies/ruby-{{ ruby_version }}/bin"
    rvm:      "{{ ruby.rvm.home }}/bin/rvm"

- debug: var=ruby_version
- debug: var=ruby_bin

- name: Downloading RVM installation script
  get_url:
    url:   "{{ ruby.rvm.url }}"
    dest:  "{{ rvm_sh }}"
    force: yes

- name: Chmoding RVM installation script
  file:
    name:  "{{ rvm_sh }}"
    state: file
    mode:  "{{ common.mode.script }}"

- name:    Installing RVM
  shell:   "{{ rvm_sh }}"

- name:    Running RVM version
  command: "{{ rvm }} --version"

- name:     Installing Ruby
  command:  "{{ rvm }} install '{{ ruby_version }}'"

- name:   Creating PATH script
  template:
    src:  ruby.sh
    dest: "{{ ubuntu.envs_dir }}"

- name:     Running Ruby binaries
  command:  "{{ ruby_bin }}/{{ item }} --version"
  with_items:
    - gem
    - rake

- name:     Running Ruby version
  command:  "{{ ruby_bin }}/ruby --version"
  register: ruby_version_out
- debug:    var=ruby_version_out.stdout

- name: Verifying Ruby version
  assert:
    that:
      - ruby_version in ruby_version_out.stdout
      - "'ruby'      in ruby_version_out.stdout"

- name: Installing Ruby gems
  gem:
    executable:   "{{ ruby_bin }}/gem"
    name:         "{{ item }}"
    user_install: no
  with_items: ruby.gems.keys()

- name:       Verifying Ruby gems
  command:    "{{ item }}"
  with_items: ruby.gems.values()
