---
- name: Calculating Ruby version
  set_fact:
    ruby_version:    "{{ ruby.version | calculate( ruby ) }}"
    additional_envs: ""

- name:    Running 'rbenv' install
  include: rbenv.yml
  when:    "{{ ruby.installer == 'rbenv' }}"

- name:    Running 'rvm' install
  include: rvm.yml
  when:    "{{ ruby.installer == 'rvm' }}"

- name:     Running Ruby version
  command:  "{{ ruby_bin }}/ruby --version"
  register: ruby_version_out
- debug:    var=ruby_version_out.stdout

- name: Verifying Ruby version
  assert:
    that:
      - ruby_version in ruby_version_out.stdout
      - "'ruby'      in ruby_version_out.stdout"
