---
- set_fact:
    rvm_sh:  /opt/rvm.sh
    rvm_bin: "{{ ruby.rvm.home }}/bin/rvm"

- get_url:
    url:   "{{ ruby.rvm.url }}"
    dest:  "{{ rvm_sh }}"
    force: "{{ ruby.rvm.redownload }}"

- file:
    name:  "{{ rvm_sh }}"
    state: file
    mode:  0744

- shell:   "{{ rvm_sh }}"

- command: "{{ rvm_bin }} --version"
  register: rvm_version

- debug: var=rvm_version.stdout

- lineinfile:
    dest: "{{ ubuntu.env_file }}"
    line: PATH="{{ ruby.rvm.home }}/bin:$PATH"

- set_fact: ruby_version="{{ ruby.version | calculate( ruby.latest ) }}"
- debug:    var=ruby_version

- apt:  name={{ item }} state=latest force=yes
  with_items:
    - build-essential

- command: "{{ rvm_bin }} install {{ ruby_version }}"
