---
- name: Calculating Ruby version
  set_fact:
    ruby_version:    "{{ ruby.version | calculate( ruby.latest ) }}"
    additional_envs: ""

- name:    Running 'rbenv' install
  include: rbenv.yml
  when:    "{{ ruby.installer == 'rbenv' }}"

- name:    Running 'rvm' install
  include: rvm.yml
  when:    "{{ ruby.installer == 'rvm' }}"

- include: "{{ common.utils.run }}"
  vars:
    title: Ruby checks
    command: { run: "{{ ruby_bin }}/ruby --version", expect: "ruby {{ ruby_version }}" }
