---
# ---------------
# https://rvm.io/
# ---------------

- set_fact:
    install_rvm:  '/opt/install-rvm.sh'
    install_ruby: '/opt/install-ruby.sh'
    rvm_source_script: "{{ ubuntu.envs_dir }}/source-rvm.sh"
    rvm:               "{{ ruby.rvm.home }}/bin/rvm"
    ruby_bin:          "{{ ruby.rvm.home }}/rubies/ruby-{{ ruby_version }}/bin"
    gems_bin:          "{{ ruby.rvm.home }}/gems/ruby-{{ ruby_version }}/bin"

- name: Downloading RVM installation script
  get_url:
    url:   "{{ ruby.rvm.url }}"
    dest:  "{{ install_rvm }}"
    force: yes

- name: Creating RVM source script
  lineinfile:
    dest:   "{{ rvm_source_script }}"
    line:   "source {{ ruby.rvm.home }}/scripts/rvm"
    create: yes
  when: not is_docker|bool

- name: Writing templates
  template:
    src:  "{{ item.src  }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'gemrc',           dest: "{{ ruby.gemrc }}"   }
    - { src: 'install-ruby.sh', dest: "{{ install_ruby }}" }

- name:    Running RVM and Ruby installation script
  command: "{{ ubuntu.bash }} '{{ item }}'"
  with_items:
    - "{{ install_rvm  }}"
    - "{{ install_ruby }}"
