---
- set_fact: etcd_dir="{{ helios.master.etcd.dir_name.replace( '<version>', helios.master.etcd.version ) }}"
- set_fact: 
    etcd_src: "{{ helios.master.etcd.home }}/{{ etcd_dir }}/etcd"
    etcd_bin: "{{ ubuntu.bin_dir }}/etcd"

- name: Downloading etcd
  get_url:
    url:  "{{ helios.master.etcd.url.replace( '<version>', helios.master.etcd.version ).replace( '<dirname>', etcd_dir ) }}"
    dest: "{{ helios.master.etcd.archive }}"
    
- file: path="{{ helios.master.etcd.home }}" state=directory
- name: Unpacking etcd
  unarchive:
    src:  "{{ helios.master.etcd.archive }}"
    dest: "{{ helios.master.etcd.home }}"
    copy: no       

- name: Stopping etcd service
  service: name=etcd state=stopped
  ignore_errors: yes

- name: Copying etcd executable
  command: cp "{{ etcd_src }}" "{{ etcd_bin }}"

- name:     Running etcd
  command:  etcd --version
  register: etcd_out
  
- name: Verifying etcd version
  assert:
    that:
      - "'etcd version {{ helios.master.etcd.version }}' in etcd_out.stdout"

- command: mkdir -p $(dirname '{{ helios.master.etcd.config }}')
- name: Copying etcd config
  template:
    src:  etcd-config
    dest: "{{ helios.master.etcd.config }}"
    
- name: Generating etcd upstart script
  template:
    src:  etcd-upstart
    dest: "{{ ubuntu.init_dir }}/etcd.conf"  

- name: Starting etcd service
  service: name=etcd state=restarted enabled=yes

- name: Verifying etcd endpoint
  wait_for: port={{ registry_port }} timeout=3
