---
- name: Setting up Exhibitor variables
  set_fact:
    exhibitor_version: "{{ helios.master.exhibitor.version | calculate( helios.master.exhibitor.latest ) }}"
- set_fact:
    exhibitor_jar:     "{{ helios.master.exhibitor.home }}/build/libs/exhibitor-{{ exhibitor_version }}.jar"
- stat: path={{ exhibitor_jar }}
  register: exhibitor_jar_stat

- name: Cloning Gradle provider
  git:
    repo: "{{ helios.master.exhibitor.gradle_provider }}"
    dest: "{{ helios.master.exhibitor.home }}"
  when: ( not exhibitor_jar_stat.stat.exists | bool )

- name: Writing Exhibitor build file
  template:
    src:  exhibitor-build.gradle
    dest: "{{ helios.master.exhibitor.home }}/build.gradle"
  when: ( not exhibitor_jar_stat.stat.exists | bool )

- name: Building Exhibitor standalone
  command: ./gradlew clean jar
  args:
    chdir: "{{ helios.master.exhibitor.home }}"
  when: ( not exhibitor_jar_stat.stat.exists | bool )

- name:     Running Exhibitor standalone help
  command:  java -jar '{{ exhibitor_jar }}' --help
  register: exhibitor_help_out

- name:  Verifying Exhibitor standalone help
  assert:
    that:
      - "'Exhibitor v{{ exhibitor_version }}' in exhibitor_help_out.stdout"
      - "'Print this help'                    in exhibitor_help_out.stdout"
      - "'Default Property Names'             in exhibitor_help_out.stdout"

- name: Generating Exhibitor upstart script
  template:
    src:  exhibitor-upstart
    dest: "{{ ubuntu.init_dir }}/exhibitor.conf"

- name: Starting Exhibitor service
  service: name=exhibitor state=started enabled=yes
