---
- include: zookeeper.yml

- include: exhibitor.yml

- name: Copying Helios master config
  copy:
    src:  helios-master
    dest: "{{ helios.master.config }}"

- name: Installing Helios master
  apt:  deb="{{ helios.packages }}/helios-master_{{ helios_version }}_all.deb"

- name: Starting Helios master service
  service: name=helios-master state=restarted enabled=yes
