---
- name: Downloading SkyDNS
  command: go get '{{ helios.master.skydns.url }}'
  environment:
    "{{ go_env }}"

- name: Building SkyDNS
  command: go build -v
  args:
    chdir: "{{ go.path }}/src/{{ helios.master.skydns.url }}"
  environment:
    "{{ go_env }}"

- name: Copying SkyDNS config
  copy:
    src:  skydns
    dest: "{{ helios.master.skydns.config }}"
