---
- include: ../download-unpack.yml
  vars:
    name:    SkyDNS
    url:     "{{ helios.master.skydns.url     | tokens( helios.master.skydns ) }}"
    archive: "{{ helios.master.skydns.archive | tokens( helios.master.skydns ) }}"
    home:    "{{ helios.master.skydns.home }}"
  
