---
- debug: var=zookeeper_port

- name: Installing ZooKeeper service
  apt: name=zookeeperd

- name: Setting up ZooKeeper port
  # http://zookeeper.apache.org/doc/r3.4.6/zookeeperAdmin.html#sc_zkMulitServerSetup
  lineinfile: 
    dest:   "{{ helios.master.zookeeper.config }}"
    line:   "clientPort={{ zookeeper_port }}"
    regexp: '^clientPort=\d+$'
        
- name: Restarting ZooKeeper service
  service: name=zookeeper state=restarted enabled=yes

- name: Checking ZooKeeper service
  wait_for: port={{ zookeeper_port }} timeout=3
