---
- debug: msg="consul_role = '{{ consul_role }}'"
- debug: msg="domain = '{{ domain }}'"
- debug: msg="consul_servers = {{ consul_servers }}"

- name: Calculating Consul version
  set_fact:
    consul_version:   "{{ consul.version | calculate( consul.latest ) }}"
    is_consul_server: "{{ consul_role == 'server' }}"
    is_consul_client: "{{ consul_role == 'client' }}"

- set_fact: consul_command="consul agent -server -config-file='{{ consul.config }}' -bootstrap-expect 1"
  when:     is_consul_server|bool

- set_fact: consul_command="consul agent -config-file='{{ consul.config }}'"
  when:     is_consul_client|bool

- debug: var=is_consul_server
- debug: var=is_consul_client
- debug: msg="consul_command = {{ consul_command }}"

# https://www.consul.io/intro/getting-started/agent.html
# https://www.consul.io/intro/getting-started/join.html

- include: "{{ common.utils.service }}"
  vars:
    title:   Consul
    service: consul
    url:     "{{ consul.url     | tokens({ 'version': consul_version }) }}"
    archive: "{{ consul.archive | tokens({ 'version': consul_version }) }}"
    home:    "{{ consul.home }}"
    env:     "{{ consul_env }}"
    configs:
      - { from: config.json, to: "{{ consul.config }}" }
    tests:
      - { run: consul --version, expect: 'Consul v{{ consul_version }}' }
      - { run: consul version,   expect: 'Consul v{{ consul_version }}' }
      - { run: consul,           expect: [ Available commands are, agent, keygen ]}
      - { run: consul --help,    expect: [ Available commands are, agent, keygen ]}
    command: "{{ consul_command }}"
    verify:  "{{ consul.verify }}"
    port:    "{{ consul.ports.http }}"
    tests_after:
      - { run:    consul members,
          expect: [ Node, Address, Status, Type, Build, Protocol, 'alive\s+(server|client)\s+{{ consul_version }}' ] }
      - { run:    consul info,
          expect: [ 'agent:', 'build:', 'consul:', 'runtime:', 'serf_lan:' ] }

- include: "{{ common.utils.run }}"
  vars:
    title: Consul server
    commands:
      - { run:    'dig @{{ common.net.localhost }}',
          expect: ';; SERVER: {{ common.net.local_ip }}#{{ common.net.ports.dns }}({{ common.net.local_ip }})' }
  when: is_consul_server|bool

- include: "{{ common.utils.run }}"
  vars:
    title: Consul client
    env:   "{{ consul_env }}"
    commands:
      - { run:    'dig @{{ consul_servers|first }}',
          expect: ';; SERVER: {{ consul_servers|first }}#{{ common.net.ports.dns }}({{ consul_servers|first }})' }
      - { run:    'dig @{{ consul_servers|last }}',
          expect: ';; SERVER: {{ consul_servers|last }}#{{ common.net.ports.dns }}({{ consul_servers|last }})' }
      - { run:    'dig @{{ consul_servers|random }}',
          expect: ';; SERVER: ' }
      - { run:    "consul join '{{ consul_servers|first }}'",
          expect: Successfully joined cluster }
      - { run:    "consul join '{{ consul_servers|last }}'",
          expect: Successfully joined cluster }
      - { run:    "consul join '{{ consul_servers|random }}'",
          expect: Successfully joined cluster }
      - { run:    "consul members",
          expect: [ '^{{ ansible_hostname }}\s+.+:{{ consul.ports.gossip }}\s+alive\s+client\s+{{ consul_version }}\s+\d+$',
                    '{{ item }}:{{ consul.ports.gossip }}\s+alive\s+server\s+{{ consul_version }}' ] }
  when: is_consul_client|bool
