---
artifactory: {
  version: latest, # 3.4.2, latest - https://dl.bintray.com/jfrog/artifactory/
  port:    8080,
  timeout: 60,         # in seconds
  run:     standalone, # standalone, war
  latest: {
    command: "curl -Ls '{{ common.urls.bintray }}/jfrog/artifactory/' | grep '<pre>' | grep 'artifactory-' | sed -r 's/<[^>]+>//g' | sed 's/artifactory-//' | sed 's/\\.zip$//' | tail -1",
    pattern: '^\d+\.\d+\.\d+$'
  },
  standalone: {
    url:     '{{ common.urls.bintray }}/jfrog/artifactory/artifactory-<version>.zip',
    archive: /opt/artifactory-<version>.zip,
    home:    /opt/artifactory
  },
  war: {
    url:          '{{ common.urls.jfrog }}/artifactory/libs-releases/org/artifactory/artifactory-web-war/<version>/artifactory-web-war-<version>.war',
    archive:      /opt/artifactory-<version>.war,
    java_options: '-server -Xms512m -Xmx2g -Xss256k -XX:PermSize=128m -XX:+UseG1GC -Djruby.compile.invokedynamic=false',
    home:         /opt/artifactory
  },
  wait: [
    { path: /artifactory/api/system/ping, content: OK }
  ],
  verify: [
    { path: /artifactory/api/application.wadl,         content: </application> },
    { path: '/artifactory/api/search/artifact?name=x', content: results },
    { path: /artifactory/webapp/home.html,             content: Artifactory },
    { path: /artifactory/webapp/browserepo.html,       content: Artifactory }
  ],
  auth: {
    user: admin,
    pass: password
  },
  import: {
    archive: /opt/repo-import.<ext>,
    home:    /opt/repo-import,
    repo:    libs-release-local
  },
  mysql: {
    enabled:   false,
    database:  artifactory,
    user:      artifactory,
    password:  artifactory_password,
    connector: {
      # http://dev.mysql.com/downloads/connector/j/
      url:     'https://cdn.mysql.com/Downloads/Connector-J/mysql-connector-java-5.1.34.zip',
      archive: /opt/mysql-connector-5.1.34.zip,
      home:    /opt/mysql-connector
    }
  },
  # https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-ArtifactSearch%28QuickSearch%29
  # https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-DeployArtifact
  # https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-DeployArtifactbyChecksum
  path: {
    artifact:     /artifactory/<repo>/<artifact>,
    upload: {
      path:       /artifactory/libs-release-local/<artifact>,
      method:     PUT,
      headers:    {
        'X-Checksum-Deploy': 'true',
        'X-Checksum-Sha1':   '<sha1>'
      }
    },
    search: {
      quick:      '/artifactory/api/search/artifact?name=<name>',
      groupId:    '/artifactory/api/search/gavc?g=<g>',
      artifactId: '/artifactory/api/search/gavc?a=<a>',
      version:    '/artifactory/api/search/gavc?v=<v>',
      gav:        '/artifactory/api/search/gavc?g=<g>&a=<a>&v=<v>'
    }
  }
}
