
etcd: {
  version:  2.0.0-rc.1, # https://github.com/coreos/etcd/releases
  dir_name: etcd-v<version>-linux-amd64,
  url:      '{{ common.github }}/coreos/etcd/releases/download/v<version>/<dir_name>.tar.gz',
  archive:  /opt/etcd-<version>.tar.gz,
  home:     /opt/etcd,
  config:   "{{ ubuntu.etc_default }}/etcd"
}

skydns: {
  version: 2.0.1d, # https://github.com/skynetservices/skydns/releases
  url:     github.com/skynetservices/skydns,
  config:  "{{ ubuntu.etc_default }}/skydns"
}
