---
- name: Upgrading installed packages
  apt:  upgrade=dist

- name: Installing utility packages
  apt:  name={{ item }} state=latest force=yes
  with_items: base.utils

- name: Installing python-pip
  apt:  name=python-pip state=latest force=yes

- name: Installing base pip packages
  pip:  name={{ item }} state=latest
  with_items: base.pip

- name:    Stopping and disabling Chef service, if found
  service: name=chef-client state=stopped enabled=no
  ignore_errors: yes

- name:    Stopping and disabling Puppet service, if found
  service: name=puppet state=stopped enabled=no
  ignore_errors: yes
