---
- name: Upgrading installed packages
  apt:  upgrade=dist

- name: Installing base packages
  apt:  name={{ item }} state=latest force=yes
  with_items:
    - vim
    - htop
    - wget
    - curl
    - git
    - zip
    - unzip
    - upstart
    - man
    - build-essential
    - psmisc # Needed for 'killall'

- name: Installing python-pip
  apt:  name=python-pip state=latest force=yes

- name: Installing base pip packages
  pip:  name={{ item }} state=latest
  with_items:
    - httplib2 # Missing on AWS Ubuntu AMI

- name:    Stopping and disabling Chef service, if found
  service: name=chef-client state=stopped enabled=no
  ignore_errors: yes

- name:    Stopping and disabling Puppet service, if found
  service: name=puppet state=stopped enabled=no
  ignore_errors: yes
