---
- apt:  update_cache=yes upgrade=dist

- apt:  name={{item}} state=latest
  with_items:
    - vim
    - htop
    - wget
    - curl
    - git
    - daemon

- command: service chef-client stop
  register: chef_client_service
  ignore_errors: yes

- service: name=chef-client state=stopped enabled=no
  when: chef_client_service|success
