---
- name: Updating Ubuntu repos
  replace:
    dest:    "{{ ubuntu.sources_list }}"
    regexp:  "{{ item.key | re_escape }}"
    replace: "{{ item.value }}"
    backup:  yes
  with_dict: ubuntu.apt

- name:     Listing Ubuntu repos
  shell:    grep 'http://' '{{ ubuntu.sources_list }}' | grep -v '#' | awk '{print $2}' | uniq | sort
  register: ubuntu_repos

- debug: var=ubuntu_repos.stdout_lines

- name: Updating 'apt' cache
  apt:  update_cache=yes

- name: Installing base packages
  apt:  name={{ item }} state=latest force=yes
  with_items: base.packages

- include: non-docker-setup.yml
  when:    not is_docker|bool
