---
- apt:  update_cache=yes
  when: is_docker

- apt:  update_cache=yes upgrade=dist
  when: ( not is_docker|bool )

- apt:  name={{item}} state=latest
  with_items:
    - vim
    - htop
    - wget
    - curl
    - git
    - unzip
    - daemon

- service: name=chef-client state=stopped enabled=no
  ignore_errors: yes

- service: name=puppet state=stopped enabled=no
  ignore_errors: yes
