---
- name: Updating 'apt' cache
  apt:  update_cache=yes

- name: Upgrading installed packages
  apt:  upgrade=dist
  when: ( not is_docker|bool )

- name: Installing base packages
  apt:  name={{ item }} state=latest force=yes
  with_items:
    - vim
    - htop
    - wget
    - curl
    - git
    - unzip
    - daemon
    - build-essential

- name:    Stopping and disabling Chef service, if exists
  service: name=chef-client state=stopped enabled=no
  ignore_errors: yes

- name:    Stopping and disabling Puppet service, if exists
  service: name=puppet state=stopped enabled=no
  ignore_errors: yes
