---
- name: Updating sources.list
  replace:
    dest:    "{{ ubuntu.sources_list }}"
    regexp:  '\/archive\.ubuntu\.com\/'
    replace: "/{{ ubuntu.apt_repo }}/"
    backup:  yes

- name: Updating 'apt' cache
  apt:  update_cache=yes

- name: Upgrading installed packages
  apt:  upgrade=dist
  when: ( not is_docker|bool )

- name: Installing base packages
  apt:  name={{ item }} state=latest force=yes
  with_items:
    - vim
    - htop
    - wget
    - curl
    - git
    - zip
    - unzip
    - upstart
    - man
    - build-essential
    - psmisc # Needed for 'killall'

- name:    Stopping and disabling Chef service, if exists
  service: name=chef-client state=stopped enabled=no
  ignore_errors: yes

- name:    Stopping and disabling Puppet service, if exists
  service: name=puppet state=stopped enabled=no
  ignore_errors: yes
