---
asgard: {
  user:          asgard,
  group:         asgard,
  user_home:     "{{ ubuntu.home_dir }}/asgard",
  home:          "{{ ubuntu.home_dir }}/asgard/.asgard",
  jar:           "{{ ubuntu.home_dir }}/asgard/.asgard/asgard-standalone.jar",
  log:           "{{ ubuntu.log_dir }}/asgard.log",
  pid:           "{{ ubuntu.pid_dir }}/asgard.pid",
  java:          "{{ java.home }}/bin/java",
  java_args:     -Xms256m -Xmx768m,

  # Default jar location, if executed outside Bakery
  # https://github.com/Netflix/asgard/releases
  jar_url:       'https://netflixoss.ci.cloudbees.com/job/asgard-master/lastSuccessfulBuild/artifact/asgard-standalone.jar',
}
