---
- debug: msg="Testing {{ repo_name }} repo {{ repo }}"

- file: path={{ gatling_simulations }} state=absent
- file: path={{ gatling_simulations }} state=directory

- name: Copying artifacts files
  copy:
    src:  "{{ item.value.artifacts }}"
    dest: "{{ test_repo.artifacts }}/{{ item.value.artifacts }}"
  with_dict: test_repo.simulations

- name: Generating simulations
  template:
    src:  Simulation.scala
    dest: "{{ gatling_simulations }}/{{ item.key }}.scala"
  with_dict: test_repo.simulations

- name: Running simulations
  command: gatling.sh -m --output-name '{{ repo_name }}{{ item.key }}' --simulation '{{ item.key }}' --results-folder '{{ report_dir }}'
  environment: "{{ gatling_env | expand_path( ansible_env ) }}"
  with_dict: test_repo.simulations
