---
- set_fact:
    repo: "http://{{ host }}:{{ port }}{{ path }}"

- debug: msg="Testing {{ repo_name }} repo {{ repo }} => '{{ reports_dir }}'"

- include: "{{ common.utils.mkdir }}"
  vars:
    file:  "{{ test_repo.log }}"

- name: Creating directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ test_repo.artifacts }}"
    - "{{ gatling_simulations }}"
    - "{{ reports_dir }}"

- name: Copying artifacts files
  copy:
    src:  "{{ item.artifacts }}"
    dest: "{{ test_repo.artifacts }}/{{ item.artifacts }}"
  with_items: test_repo.simulations

- name: Generating simulations
  template:
    src:  Simulation.scala
    dest: "{{ gatling_simulations }}/{{ item.name }}.scala"
  with_items: test_repo.simulations

- name: Running simulations
  command: sleep 15 && gatling.sh -m --output-name {{ repo_name }}{{ item.name }} --simulation {{ repo_name }}{{ item.name }} --results-folder '{{ reports_dir }}' >> '{{ test_repo.log }}' 2>&1
  environment: "{{ gatling_env | expand_path( ansible_env ) }}"
  with_items: test_repo.simulations
