---
- set_fact:
    repo: "http://{{ host }}:{{ port }}{{ path }}"

- debug: msg="Testing {{ repo_name }} repo {{ repo }} => '{{ reports_dir }}'"
  when:  reports_archive is not defined

- debug: msg="Testing {{ repo_name }} repo {{ repo }} => '{{ reports_dir }}' => '{{ reports_archive }}'"
  when:  reports_archive is defined

- file: path={{ reports_dir }} state=absent
  when: clean_reports | default( False )

- name: Creating directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ test_repo.files_dir }}"
    - "{{ gatling_simulations }}"
    - "{{ reports_dir }}"

- name: Copying artifacts files
  copy:
    src:  "{{ item.artifacts }}"
    dest: "{{ test_repo.files_dir }}/{{ item.artifacts }}"
  with_items: test_repo.simulations

- name: Generating simulations
  template:
    src:  Simulation.scala
    dest: "{{ gatling_simulations }}/{{ repo_name }}{{ item.name }}.scala"
  with_items: test_repo.simulations

- include: "{{ common.roles.gatling }}"
  vars:
    # Sending a list of simulation names: ArtifactoryWarmup, ArtifactoryGet50, etc
    simulations: "{{ test_repo.simulations | map( attribute = 'name' ) | transform( repo_name + '{0}' ) }}"
