---
- debug:   msg="Testing {{ name }} repo '{{ repo }}'"
- include: build-applications.yml

# -----------------------------
# LoadArtifacts.scala
# -----------------------------

- name: Copying artifacts file
  copy:
    src:  load-artifacts.txt
    dest: "{{ test_repo.load.artifacts }}"

- name: Generating LoadArtifacts simulation
  template:
    src:  LoadArtifacts.scala
    dest: "{{ gatling_simulations }}/LoadArtifacts.scala"

- debug:   msg="Running '{{ name }}-' LoadArtifacts simulation => '{{ report }}'"
- name:    Running LoadArtifacts simulation
  command: gatling.sh -m --output-name '{{ name }}' --simulation LoadArtifacts --results-folder '{{ report }}'
  environment: "{{ gatling_env | expand_path( ansible_env ) }}"
