---
- debug: msg="Running simulation of {{ repo_name }} repo '{{ repo }}' => '{{ report_dir }}'"

- file: path={{ gatling_simulations }} state=absent
- file: path={{ gatling_simulations }} state=directory

- include: run-simulation.yml simulation=load_artifacts
- include: run-simulation.yml simulation=get_artifacts_10
- include: run-simulation.yml simulation=get_artifacts_30
