---
- debug: msg="Testing {{ repo_name }} repo {{ repo }}"

- file: path={{ gatling_simulations }} state=absent
- file: path={{ gatling_simulations }} state=directory

- include: run-simulation.yml name=LoadArtifacts
- include: run-simulation.yml name=GetArtifacts10
- include: run-simulation.yml name=GetArtifacts30
