---
- debug:   msg="Testing repo '{{ repo }}'"
- include: build-applications.yml

# -----------------------------
# LoadArtifacts.scala
# -----------------------------

- name: Copying artifacts file
  copy:
    src:  load-artifacts.txt
    dest: "{{ test_repo.load.artifacts }}"

- name: Generating LoadArtifacts simulation
  template:
    src:  LoadArtifacts.scala
    dest: "{{ gatling_simulations }}/LoadArtifacts.scala"
