---
- set_fact:
    simulation: "{{ test_repo.simulations[ name ] }}"
- set_fact:
    artifacts:  "{{ test_repo.artifacts }}/{{ simulation.artifacts }}"
    users:      "{{ simulation.users }}"

- debug: msg="Running simulation {{ name }}. Artifacts - '{{ artifacts }}', users - {{ users }}, report - '{{ report_dir }}'"

- name: Copying artifacts file
  copy:
    src:  "{{ simulation.artifacts }}"
    dest: "{{ artifacts }}"

- name: Generating simulation
  template:
    src:  Simulation.scala
    dest: "{{ gatling_simulations }}/{{ name }}.scala"

- name:    Running simulation
  command: gatling.sh -m --output-name '{{ repo_name }}{{ name }}' --simulation '{{ name }}' --results-folder '{{ report_dir }}'
  environment: "{{ gatling_env | expand_path( ansible_env ) }}"
