---
- name: Calculating Packer version
  set_fact:
    packer_version: "{{ packer.version | calculate( packer.latest ) }}"

- include: "{{ common.utils.download }}"
  vars:
    title:   Packer
    url:     "{{ packer.url     | tokens({ 'version': packer_version })}}"
    archive: "{{ packer.archive | tokens({ 'version': packer_version })}}"
    home:    "{{ packer.home }}"
    env:
      PATH: "$PATH:{{ packer.home }}"
    tests:
      - { run: packer version, expect: "Packer v{{ packer_version }}" }
