---
# ===================================================================================================
# Downloads and unpacks an archive
# ===================================================================================================
# - Downloads {{ url }} to {{ archive }}, unpacks it to {{ home }} directory
#   {{ home }} is deleted before unpack operation, unless {{ clean }} is False
# - Runs {{ tests }}
# - Generates {{ configs }}
# - Runs {{ cleanup commands }}
# 
# ===================================================================================================
# - Required variables are: url, archive, home. Others are optional.
# ===================================================================================================

- debug: msg="Downloading '{{ url }}' => '{{ archive }}' => '{{ home }}'"

- name: Downloading {{ title }}
  get_url:
    url:  "{{ url }}"
    dest: "{{ archive }}"

- debug: msg="Deleting '{{ home }}'!"
  when: clean | default(True)

- file: path={{ home }} state=absent
  when: clean | default(True)

- file: path={{ home }} state=directory

- name: Unpacking {{ title }}
  unarchive:
    src:  "{{ archive }}"
    dest: "{{ home }}"
    copy: false
    
- name:     Running {{ title }} tests
  command:  "{{ item.run }}"
  register: test_out
  ignore_errors: yes # So we don't fail for non-zero exit code
  failed_when:   item.expect not in test_out.stdout
  with_items:
    - "{{ tests }}"
  when: tests is defined

- command: mkdir -p $(dirname {{ item.to }})
  with_items:
    - "{{ configs }}"
  when: configs is defined

- name: Generating {{ title }} configs
  template:
    src:  "{{ playbook_dir }}/roles/{{ item.role | default( service ) }}/templates/{{ item.from  }}"
    dest: "{{ item.to }}"
  with_items:
    - "{{ configs }}"
  when: configs is defined

- name: Running {{ title }} cleanup commands
  command: "{{ ubuntu.bash }} -c '{{ item }}'"
  with_items:
    - "{{ cleanup }}"
  when: cleanup is defined
