---
# ---------------------------------------------------------
# Called by other roles to register a host with SkyDNS
# ---------------------------------------------------------
- debug: msg="Sending registration request to '{{ etcd_host }}' for '{{ host }}' => '{{ ip }}'"
- debug: msg="etcd_port = '{{ etcd_port }}'"
- debug: msg="skydns_host = '{{ skydns_host }}'"

- set_fact:
    registration_url: "http://{{ etcd_host }}:{{ etcd_port }}/v2/keys/skydns/{{ '/'.join( host.split( '.' )[::-1] ) }}"
- set_fact:
    registration_command: "curl -XPUT '{{ registration_url }}' -d value='{ \"host\" : \"{{ ip }}\" }'"
    dig_command:          "dig @{{ skydns_host }} '{{ host }}'"

# https://github.com/ansible/ansible-modules-core/issues/265
# uri:
#   method:  POST
#   url:     "{{ registration_url }}"
#   body:    "{ 'host' : '{{ ip }}' }"
#   timeout: 3

- debug:    msg="Running [{{ registration_command }}] and [{{ dig_command }}]"

- command: "{{ registration_command }}"
- command: "{{ dig_command }}"
  register: dig_out

- name: Verifying dig
  assert:
    that:
      - "'{{ host }}' in dig_out.stdout"
      - "'{{ ip }}'   in dig_out.stdout"
