---
# -----------------------------------------------------------------
#   Called by other roles to register a host with SkyDNS via etcd
# -----------------------------------------------------------------
- debug:
    msg: "Sending registration request to '{{ etcd_host }}:{{ etcd_port }}': '{{ src }}' => '{{ dest }}'"

- fail: "Registration src '{{ src }}' should end with '.{{ domain }}'"
  when: not src.endswith( ".{{ domain }}" )

# https://github.com/skynetservices/skydns
# https://github.com/ansible/ansible-modules-core/issues/265
- set_fact:
    registration_url: "http://{{ etcd_host }}:{{ etcd_port }}/v2/keys/skydns/{{ '/'.join( src.split('.')[::-1] ) }}"
- set_fact:
    registration_command: "curl -XPUT '{{ registration_url }}' -d value='{\"host\":\"{{ dest }}\",\"port\":{{ port | default(0) }}}'"

- include: "{{ common.utils.run }}"
  vars:
    title: registration '{{ src }}' => '{{ dest }}'
    commands:
      - { run:    "{{ registration_command }}" }
      - { run:    "dig '@{{ etcd_host }}' '{{ src }}'",
          expect: '^{{ src }}.\s+3600\s+IN\s+\w+\s+{{ dest }}\.?$' }
