---
# ===================================================================================================
# Runs commands and verifies their output. Required variables: title, commands or command.
# ===================================================================================================
- set_fact:
    run_env: "{{ env | default({}) | expand_path( ansible_env ) }}"

- debug: msg="Running {{ title }} commands with env {{ run_env }}"
- debug: var=commands

- shell:       "{{ item.run }} 2>&1"
  environment: "{{ run_env }}"
  register:    shell_out
  failed_when: not ( shell_out.stdout_lines | default(['']) | contains( item.expect | default('') ))
  when:        item.run is defined
  with_items:  commands
