---
# ===================================================================================================
# Downloads, unpacks, installs, starts and checks a service {{ service }}, titled {{ title }}
# ===================================================================================================
# - Downloads {{ url }} to {{ archive }}, unpacks it to {{ home }} directory
#   {{ home }} is deleted before unpack, unless {{ clean }} is False
# - Writes {{ configs }}
# - Executes {{ cleanup }} commands
# - Creates an upstart script to run {{ command }} as service {{ service }} and starts it
#   upstart script attempts to load {{ env_config }} and writes log to /var/log/{{ service }}.log
# - Verifies service endpoint responds at {{ port }} within {{ timeout }} seconds
# - Verifies http://127.0.0.1:{{ port }}{{ path }} to return {{ status }} code and {{ content }}
# ===================================================================================================
# - Required variables are: service, title, command. Other are optional.
# ===================================================================================================
- debug: var=service
- debug: var=title
- debug: var=command

- name: Stopping service {{ title }}
  service: name={{ service }} state=stopped
  ignore_errors: yes

- name: Downloading {{ title }}
  get_url:
    url:  "{{ url }}"
    dest: "{{ archive }}"
  when: ( url is defined ) and ( archive is defined )

- debug: msg="Deleting '{{ home }}'!"
  when: ( home is defined ) and ( clean | default(True))

- file: path={{ home }} state=absent
  when: ( home is defined ) and ( clean | default(True))

- file: path={{ home }} state=directory
  when: home is defined

- name: Unpacking {{ title }}
  unarchive:
    src:  "{{ archive }}"
    dest: "{{ home }}"
    copy: false
  when: ( archive is defined ) and ( home is defined )

- name:     Running {{ title }} test
  command:  "{{ test.run }}"
  register: test_out
  ignore_errors: yes # We don't want to fail for non-zero exit code
  when: test is defined

- name: Verifying {{ title }} test
  assert:
    that:
      - "'{{ test.expect }}' in '{{ test_out.stdout }}'"
  when: test is defined

- command: mkdir -p $(dirname {{ item.to }})
  with_items:
    - "{{ configs }}"
  when: configs is defined

- name: Generating {{ title }} configs
  template:
    src:  "{{ playbook_dir }}/roles/{{ item.role | default( service ) }}/templates/{{ item.from  }}"
    dest: "{{ item.to }}"
  with_items:
    - "{{ configs }}"
  when: configs is defined

- name: Running {{ title }} cleanup commands
  command: "{{ ubuntu.bash }} -c '{{ item }}'"
  with_items:
    - "{{ cleanup }}"
  when: cleanup is defined

- name: Generating {{ title }} upstart script
  template:
    src:  "{{ playbook_dir }}/utils/templates/upstart"
    dest: "{{ ubuntu.init_dir }}/{{ service }}.conf"

- name: Starting {{ title }} service
  service: name={{ service }} state=started enabled=yes

- name: Verifying {{ title }} endpoint
  wait_for: port={{ port }} timeout={{ timeout | default( 5 ) }}
  when: port is defined

- name: Waiting for {{ title }} HTTP endpoint
  uri:
    url:            "http://{{ common.net.localhost }}:{{ port }}{{ item.path | default( '' )}}"
    status_code:    "{{ item.status | default( 200 )}}"
    return_content: yes
  register: http_wait_out
  until:    item.content in http_wait_out.content
  retries:  "{{ ( timeout | default( 5 )) / 3 }}"
  delay:    3
  with_items:
    - "{{ wait_for }}"
  when: ( port is defined ) and ( wait_for is defined )

- name: Verifying {{ title }} HTTP endpoint
  uri:
    url:            "http://{{ common.net.localhost }}:{{ port }}{{ item.path | default( '' )}}"
    status_code:    "{{ item.status | default( 200 )}}"
    return_content: yes
  register: http_verify_out
  with_items:
    - "{{ verify }}"
  failed_when: item.content not in http_verify_out.content
  when:        ( port is defined ) and ( verify is defined )
