---

# http://dev.mysql.com/downloads/repo/apt/
# http://dev.mysql.com/downloads/file.php?id=452447
# http://dev.mysql.com/get/mysql-apt-config_0.2.1-1ubuntu14.04_all.deb

- name: Adding MySQL repositories
  apt_repository: repo="{{ item }}" update_cache=yes
  with_items:
    - deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.6
    - deb-src http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.6

- name: Installing MySQL
  apt:  name={{ item }} state=latest force=yes
  with_items:
    - python-mysqldb
    - mysql-server

# http://stackoverflow.com/a/21151255/472153
- name: Updating '{{ mysql.my_cnf }}'
  lineinfile:
    dest: "{{ mysql.my_cnf }}"
    line: '# bind-address = {{ common.net.localhost }}'
    regexp: ^bind-address\s+=

- name: Updating '{{ mysql.my_cnf }}' for Docker
  lineinfile:
    dest: "{{ mysql.my_cnf }}"
    line: 'user            = root'
    regexp: ^user\s+=\s+mysql$
  when: is_docker|bool

- name: Starting MySQL service
  service: name=mysql state=started

- name:     Running MySQL version
  command:  mysql --version
  register: mysql_version_out

- debug: var=mysql_version.stdout

- name: Verifying MySQL version
  assert:
    that:
      - "'mysql' in mysql_version_out.stdout"
      - "'5.6'   in mysql_version_out.stdout"

- set_fact:
    remote_access_script: /etc/mysql/root_remote_access.sql

- copy:
    src:  root_remote_access.sql
    dest: "{{ remote_access_script }}"

- name:  Allowing MySQL remote access
  shell: "mysql -u root -h localhost < {{ remote_access_script }}"

- name:     Verifying MySQL databases
  mysql_db: name={{ item }} state=present login_host={{ common.net.localhost }} login_user=root login_password=''
  with_items:
    - mysql
    - information_schema
    - performance_schema

- name: Restarting MySQL service
  service: name=mysql state=restarted
  when: start_service

- name: Stopping MySQL service
  service: name=mysql state=stopped
  when: ( not start_service|bool )
