---

# http://dev.mysql.com/downloads/repo/apt/
# http://dev.mysql.com/downloads/file.php?id=452447
# http://dev.mysql.com/get/mysql-apt-config_0.2.1-1ubuntu14.04_all.deb

- apt_repository: repo="{{ item }}" update_cache=yes
  with_items:
    - deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.6
    - deb-src http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.6

- apt: name={{ item }} state=latest force=yes
  when: periodic
  with_items:
    - mysql-community-server
    - mysql-server

- command:  mysql --version
  register: mysql_version

- assert:
    that:
      - "'mysql' in mysql_version.stdout"
      - "'5.6'   in mysql_version.stdout"

# http://stackoverflow.com/a/21151255/472153
- lineinfile:
    dest: "{{ mysql.my_cnf }}"
    line: '# bind-address = 127.0.0.1'
    regexp: ^bind-address\s+=

- set_fact:
    remote_access_script: /etc/mysql/root_remote_access.sql

- name: Start MySQL service
  service: name=mysql state=started

- copy:
    src:  root_remote_access.sql
    dest: "{{ remote_access_script }}"

- shell: "mysql -u root < {{ remote_access_script }}"

- name: Stop MySQL service
  service: name=mysql state=stopped
  when: ( not mysql_start_service|bool )

- name: Restart MySQL service
  service: name=mysql state=restarted
  when: mysql_start_service
