---

- copy:
    src:  mysql.list
    dest: "{{ mysql.mysql_list }}"

- apt: update_cache=yes
  when: periodic

- apt: name=mysql-server state=latest force=yes
  when: periodic

- command:  mysql --version
  register: mysql_version

- assert:
    that:
      - "'mysql' in mysql_version.stdout"
      - "'5.6'   in mysql_version.stdout"

# http://stackoverflow.com/a/21151255/472153
- lineinfile:
    dest: "{{ mysql.my_cnf }}"
    line: '# bind-address = 127.0.0.1'
    regexp: ^bind-address\s+=

- copy:
    src:  root.sql
    dest: "{{ mysql.root_sql }}"

- shell: "mysql -u root < {{ mysql.root_sql }}"

- name: Restart MySQL
  service: name=mysql state=restarted
