---
packer: {
  version: latest, # 0.7.5, latest - https://www.packer.io/downloads.html
  latest: {
    command: "curl -Ls '{{ common.urls.bintray }}/mitchellh/packer/' | grep packer | grep linux | tail -1 | cut -d_ -f5",
    pattern: '^\d+\.\d+\.\d+$'
  },
  url:      '{{ common.urls.bintray }}/mitchellh/packer/packer_<version>_linux_amd64.zip',
  archive:  /opt/packer-<version>.zip,
  home:     /opt/packer
}
