---
helios: {
  version:       latest, # 0.8.138 or latest
  download_url:  'https://github.com/spotify/helios/releases/download',
  packages:      /opt/helios,
  latest: {
    command: "curl -s 'https://github.com/spotify/helios/releases' | grep '/spotify/helios/releases/tag/' | sed -r 's/<[^>]+>//g' | sed -r 's/:.+//' | sed '/^\\s*$/d' | head -1 | awk '{print $1}'",
    pattern: '^\d+\.\d+\.\d+$'
  },
  master: {
    config:  /etc/default/helios-master,
    exhibitor: {
      version: latest, # 1.5.2 or latest
      gradle_provider: 'https://github.com/evgeny-goldin/gradle-provider.git',
      home:            /opt/exhibitor,
      latest: {
        command: "curl -s 'http://jcenter.bintray.com/com/netflix/exhibitor/exhibitor-standalone/' | grep '<pre>' | grep -v 'maven-metadata.xml' | sed -r 's/<[^>]+>//g' | tr -d '/' | tail -1",
        pattern: '^\d+\.\d+\.\d+$'
      }
    },
    zookeeper: {
      config: /etc/zookeeper/conf/zoo.cfg
    },
    etcd: {
      version:  0.4.6,
      dir_name: etcd-v<version>-linux-amd64,
      url:      'https://github.com/coreos/etcd/releases/download/v<version>/<dirname>.tar.gz',
      archive:  /opt/etcd.tar.gz,
      home:     /opt/etcd,
      config:   /etc/etcd/etcd.conf
    },
    skydns: {
      
    }
  },
  agent: {
    home:      ~/.helios,
    config:    /etc/default/helios-agent,
    state_dir: /var/lib/helios-agent,
    registrar_plugin: {
      url: 'https://github.com/spotify/helios-skydns/releases/download/0.1/helios-skydns-0.1.jar',
      jar: /opt/helios-skydns.jar
    }
  }
}
