---
- name: Installing Node.js packages
  apt:  name={{ item }} state=latest force=yes
  with_items:
    - nodejs
    - npm

- file:
    path:  /usr/bin/nodejs
    state: file

- name: Linking 'nodejs' as 'node'
  file:
    src:   /usr/bin/nodejs
    dest:  /usr/bin/node
    state: link

- name:    Running Node.js version
  command: node --version

- name:    Running Npm version
  command: npm  --version

- name: Installing Node.js global packages
  npm:  name={{ item }} global=yes production=yes
  with_items:
    - grunt-cli
    - bower

- name:    Running Grunt version
  command: grunt --version

- name:    Running Bower version
  command: bower --version
