---
- apt: name={{ item }} state=latest force=yes
  with_items:
    - nodejs
    - npm

- file:
    path:  /usr/bin/nodejs
    state: file

- file:
    src:   /usr/bin/nodejs
    dest:  /usr/bin/node
    state: link

- command: node --version
- command: npm  --version

- npm:  name={{ item }} global=yes production=yes
  with_items:
    - grunt-cli
    - bower

- command: grunt --version
- command: bower --version
