---
# http://www.duinsoft.nl/packages.php

- file: name=/tmp/update-sun-jre/            state=absent
- file: name="{{ java.jre.installer_home }}" state=absent
  when: java.jre.redownload
- file: name="{{ java.jre.installer_home }}" state=directory

- set_fact:
    installer_jre_version: ''

- set_fact:
    installer_jre_version: '-7'
  when: java.version == 7

- name: Downloading JRE installer
  get_url:
    url:   "{{ java.jre.installer_url }}"
    dest:  "{{ java.jre.installer_home }}/{{ java.jre.installer_bin }}"
    force: "{{ java.jre.redownload }}"

- name:  Running JRE installer
  command: "{{ item }}"
  args:
    chdir: "{{ java.jre.installer_home }}"
  with_items:
    - "bash ./{{ java.jre.installer_bin }} -x"
    - "./{{ java.jre.installer_script }} {{ installer_jre_version }} -c -i install"
