---

# https://coderwall.com/p/zzdapg

- command: java -version
  register: java_version
  ignore_errors: yes

- set_fact: java_installed={{ java_version|success }}
- debug: var=java_installed

- apt_repository: repo=ppa:webupd8team/java state=present
  when: ( not java_installed|bool )

- shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  when: ( not java_installed|bool )

- apt: name=oracle-java7-installer state=latest update-cache=yes force=yes
  when: ( not java_installed|bool )

- lineinfile:
    dest: "{{ ubuntu.env_file }}"
    line: JAVA_HOME="{{ java.home }}"

- shell: java -version 2>&1
  register: java_version_1

- shell: "{{ java.home }}/bin/java -version 2>&1"
  register: java_version_2

- assert:
    that:
      - java_version_1.stdout == java_version_2.stdout
      - "{{ '1.7.0' in java_version_1.stdout }}"
      - "{{ 'Java(TM) SE Runtime Environment' in java_version_1.stdout }}"
