---
# https://help.ubuntu.com/community/Java

- name:    Running JRE installer
  include: jre.yml
  when:    java.jre_or_jdk == 'jre'

- name:    Running JDK installer
  include: jdk.yml
  when:    java.jre_or_jdk == 'jdk'

- name:     Running Java
  shell:    java -version 2>&1
  register: java_out
- debug:    var=java_out.stdout

- name:  Verifying Java version
  assert:
    that:
      - "'1.{{ java.version }}'            in java_out.stdout"
      - "'Java(TM) SE Runtime Environment' in java_out.stdout"

- name:     Running Javac
  shell:    javac -help 2>&1
  register: javac_out
  when:     java.jre_or_jdk == 'jdk'

- name:  Verifying Javac
  assert:
    that:
      - "'Usage'                in javac_out.stdout"
      - "'-bootclasspath'       in javac_out.stdout"
      - "'Generate no warnings' in javac_out.stdout"
  when: java.jre_or_jdk == 'jdk'
