---
# https://coderwall.com/p/zzdapg

- name: Adding Java repository
  apt_repository: repo=ppa:webupd8team/java state=present update-cache=yes
- shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Downloading and installing Java
  apt:  name=oracle-java7-installer state=latest force=yes

- name: Adding JAVA_HOME
  lineinfile:
    dest: "{{ ubuntu.env_file }}"
    line: JAVA_HOME="{{ java.home }}"

- name:     Running Java version (full path)
  shell:    "{{ java.home }}/bin/java -version 2>&1"
  register: java_version_out_1

- name:     Running Java version (just 'java')
  shell:    java -version 2>&1
  register: java_version_out_2

- name:  Verifying Java version
  assert:
    that:
      - java_version_out_1.stdout == java_version_out_2.stdout
      - "'1.7.0'                           in java_version_out_1.stdout"
      - "'Java(TM) SE Runtime Environment' in java_version_out_1.stdout"
