---
# https://help.ubuntu.com/community/Java
- set_fact:  java_distribution={{ java_distribution | default( java.default_distribution ) }}
- debug: var=java_distribution

- include: open_jdk.yml
  when:    java_distribution == 'open_jdk'

- include: oracle_jdk.yml
  when:    java_distribution == 'oracle_jdk'

- include: oracle_jre.yml
  when:    java_distribution == 'oracle_jre'

- debug: msg="JAVA_HOME is set to '{{ java_home }}'"

- include: "{{ common.utils.run }}"
  vars:
    title:   OpenJDK java/javac
    commands:
      - { run: '"{{ java_home }}/bin/java"  -version', expect: [ 'OpenJDK Runtime Environment', 'OpenJDK 64-Bit Server VM' ] }
      - { run: '"{{ java_home }}/bin/javac" -version', expect: 'javac' }
  when: java_distribution == 'open_jdk'

- include: "{{ common.utils.run }}"
  vars:
    title:   Oracle java
    command: { run: '"{{ java_home }}/bin/java" -version', expect: [ '1.{{ java.version }}', 'Java(TM) SE Runtime Environment' ] }
  when: java_distribution in [ 'oracle_jre', 'oracle_jdk' ]

- include: "{{ common.utils.run }}"
  vars:
    title:   Oracle javac
    command: { run: '"{{ java_home }}/bin/javac" -version', expect: 'javac 1.{{ java.version }}' }
  when: java_distribution == 'oracle_jdk'

- name: Generating Java environment variables file
  lineinfile:
    dest:   "{{ ubuntu.envs_dir }}/java.sh"
    create: yes
    line:   'export {{ item.key }}="{{ item.value }}"'
  with_dict:
    JAVA_HOME: "{{ java_home }}"
    PATH:      "$PATH:{{ java_home }}/bin"
