---
# http://www.duinsoft.nl/packages.php

- file: name=/tmp/update-sun-jre/        state=absent
- file: name="{{ java.installer.home }}" state=directory

- set_fact:
    installer_bin:         "{{ java.installer.home }}/update-sun-jre.bin"
    installer_script:      "{{ java.installer.home }}/update-sun-jre"
    installer_jre_version: ''

- set_fact:
    installer_jre_version: '-7'
  when: java.version == 7

- name: Downloading Java installer
  get_url: url={{ java.installer.url }} dest="{{ installer_bin }}"

- name:  Run Java installer
  command: "{{ item }}"
  args:
    chdir: "{{ java.installer.home }}"
  with_items:
    - "bash {{ installer_bin }} -x"
    - "{{ installer_script }} {{ installer_jre_version }} -c -i install"

- name:     Running Java version
  shell:    java -version 2>&1
  register: java_version_out
- debug:    var=java_version_out.stdout

- name:  Verifying Java version
  assert:
    that:
      - "'1.{{ java.version }}'            in java_version_out.stdout"
      - "'Java(TM) SE Runtime Environment' in java_version_out.stdout"
