---
# http://www.duinsoft.nl/packages.php

- file: name=/tmp/update-sun-jre/                   state=absent
- file: name="{{ java.oracle_jre.installer_home }}" state=absent
  when: java.oracle_jre.redownload
- file: name="{{ java.oracle_jre.installer_home }}" state=directory

- set_fact:
    installer_jre_version: ''

- set_fact:
    installer_jre_version: '-7'
  when: java.version == 7

- name: Downloading Oracle JRE installer
  get_url:
    url:   "{{ java.oracle_jre.installer_url }}"
    dest:  "{{ java.oracle_jre.installer_home }}/{{ java.oracle_jre.installer_bin }}"
    force: "{{ java.oracle_jre.redownload }}"

- name:  Running Oracle JRE installer
  command: "{{ item }}"
  args:
    chdir: "{{ java.oracle_jre.installer_home }}"
  with_items:
    - "bash ./{{ java.oracle_jre.installer_bin }} -x"
    - "./{{ java.oracle_jre.installer_script }} {{ installer_jre_version }} -c -i install"

- name: Calculating Java home directory
  shell:    ls '{{ java.oracle_jre.java_home_base }}' | grep jre | sort | tail -1
  register: java_home_dir

- name: Setting java_home
  set_fact:
    java_home: "{{ java.oracle_jre.java_home_base }}/{{ java_home_dir.stdout }}"
