---
test_repo: {
  artifacts: /opt,
  simulations: {
    Warmup: {
      artifacts: all-artifacts-size-sorted.txt,
      users:     1
    },
    Get30: {
      artifacts: all-artifacts-name-sorted.txt,
      users:     30
    }
  }
}
