---
test_repo: {
  files_dir: /opt,
  simulations: [
    { name: Warmup,               users: 1,   artifacts: all-artifacts-size-sorted.txt },
    { name: Get100,               users: 100, artifacts: all-artifacts-name-sorted.txt },
    { name: Get400,               users: 400, artifacts: all-artifacts-name-sorted.txt },
    { name: QuickSearch100,       users: 100, artifacts: all-artifacts-name-sorted.txt, search: quick },
    { name: GroupIdSearch100,     users: 100, artifacts: all-artifacts-name-sorted.txt, search: groupId },
    { name: ArtifactIdSearch100,  users: 100, artifacts: all-artifacts-name-sorted.txt, search: artifactId },
    { name: VersionSearch100,     users: 100, artifacts: all-artifacts-name-sorted.txt, search: version },
    { name: GavSearch100,         users: 100, artifacts: all-artifacts-name-sorted.txt, search: gav },
    { name: GetUpload100,         users: 100, artifacts:    all-artifacts-name-sorted.txt,
                                              upload:       all-artifacts-name-sorted.txt,
                                              upload_ratio: 10 }
  ],
  upload: {
    archive: /opt/upload.<ext>,
    home:    /opt/upload
  },
  detailed_reports: false
}
