---
- include: "{{ common.utils.download }}"
  vars:
    title:   Nexus import archive
    url:     "{{ import }}"
    archive: "{{ nexus.import.archive | tokens({ 'ext' : import | ext }) }}"
    home:    "{{ nexus_storage }}/{{ nexus.import.repo }}"
    clean:   false

# https://support.sonatype.com/entries/38605563-Can-I-directly-update-artifacts-in-Nexus-local-storage-on-disk-

- name: Asking Nexus to rebuild the index
  uri:
    url:         "http://{{ common.net.localhost }}:{{ nexus_port }}/nexus/service/local/{{ item }}"
    user:        "{{ nexus.auth.user }}"
    password:    "{{ nexus.auth.pass }}"
    method:      DELETE
    status_code: 202,204
  with_items:
    - "repositories/{{ nexus.import.repo }}/routing"
    - "metadata/repositories/{{ nexus.import.repo }}/content/"
    - "data_index/repositories/{{ nexus.import.repo }}/content"

- name: Waiting for Nexus to rebuild the index
  uri:
    url:     "http://{{ common.net.localhost }}:{{ nexus_port }}/nexus/service/local/lucene/search?q=o"
    timeout: 5
    return_content: yes
  register: nexus_search
  until:    "{{ ( nexus_search.content is defined ) and ( not ( '<totalCount>0</totalCount>' in nexus_search.content )) }}"
  retries:  200
  delay:    3
