---
- set_fact:
    nexus_port:   "{{ repo_port    | default( nexus.port ) }}"
    java_options: "{{ java_options | default( '' ) }}"

- name:    Stopping and disabling Artifactory service, if found
  service: name=artifactory state=stopped enabled=no
  ignore_errors: yes

- include: standalone.yml
  when:    nexus.run == 'standalone'

- include: war.yml
  when:    nexus.run == 'war'

- include: import.yml
  when:    import is defined
