---
- set_fact:
    nexus_port:   "{{ port         | default( nexus.port ) }}"
    java_options: "{{ java_options | default( '' ) }}"

- debug: msg="Running Nexus on port {{ nexus_port }}, Java options '{{ java_options }}'"

- name:    Stopping and disabling Artifactory service, if found
  service: name={{ item }} state=stopped enabled=no
  ignore_errors: yes
  with_items:
    - artifactory
    - mysql

- include: standalone.yml
  when:    nexus.run == 'standalone'

- include: war.yml
  when:    nexus.run == 'war'

- include: import.yml
  when:    import is defined
