---
- set_fact:
    nexus_home:   "{{ nexus.standalone.home }}/nexus-{{ nexus.version }}"
- set_fact:
    wrapper_conf: "{{ nexus_home }}/bin/jsw/conf/wrapper.conf"

- include: "{{ common.utils.service }}"
  vars:
    service: nexus
    title:   Nexus
    url:     "{{ nexus.standalone.url     | tokens( nexus ) }}"
    archive: "{{ nexus.standalone.archive | tokens( nexus ) }}"
    home:    "{{ nexus.standalone.home }}"
    env:
      RUN_AS_USER: root
    configs:
      - { from: nexus.properties,  to: "{{ nexus_home }}/conf/nexus.properties" }
      - { from: update-wrapper.sh, to: "{{ nexus_home }}/update-wrapper.sh", mode: '0744' }
    cleanup:
      - "{{ nexus_home }}/update-wrapper.sh"
    command: "{{ nexus_home }}/bin/nexus console"
    port:    "{{ nexus_port }}"
    timeout: "{{ nexus.timeout }}"
    wait:    "{{ nexus.wait }}"
    verify:  "{{ nexus.verify }}"
