---
- set_fact:
    nexus_port: "{{ nexus_port | default( nexus.port ) }}"
    nexus_home: "{{ nexus.standalone.home }}/nexus-{{ nexus.version }}"
    
- include: "{{ common.utils.service }}"
  vars:
    service:  nexus
    title:    Nexus
    url:      "{{ nexus.standalone.url     | tokens( nexus ) }}"
    archive:  "{{ nexus.standalone.archive | tokens( nexus ) }}"
    home:     "{{ nexus.standalone.home }}"
    configs:
      - { from: nexus.sh,         to: "{{ ubuntu.envs_dir }}/nexus.sh" }
      - { from: nexus.properties, to: "{{ nexus_home }}/conf/nexus.properties" }
    env_config: "{{ ubuntu.envs_dir }}/nexus.sh"        
    command:    "{{ nexus_home }}/bin/nexus console"
    port:       "{{ nexus_port }}"
    timeout:    60
