---
- include: "{{ common.roles.tomcat }}"
  vars:
    tomcat_port:   "{{ nexus_port }}"
    catalina_opts: "-Xms256m -Xmx768m -XX:MaxPermSize=192m -Djava.io.tmpdir=./tmp -Djava.net.preferIPv4Stack=true {{ java_options }}"

- include: "{{ common.utils.service }}"
  vars:
    service: nexus
    title:   Nexus
    url:     "{{ nexus.war.url     | tokens( nexus ) }}"
    archive: "{{ nexus.war.archive | tokens( nexus ) }}"
    home:    "{{ tomcat_webapps }}/{{ nexus.war.home }}"
    command: "{{ tomcat_run  }}"
    port:    "{{ nexus_port }}"
    timeout: "{{ nexus.timeout }}"
    wait:    "{{ nexus.wait }}"
    verify:  "{{ nexus.verify }}"
