---
# Ansible playbook for Ubuntu
# http://www.ansible.com/

- name:  Ansible
  hosts: all
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: periodic-before, period: "{{ 24 * 3600 }}" }
    - { role: base, when: periodic }
    - ansible
    - periodic-after
