---
# Artifactory playbook for Ubuntu
# http://www.jfrog.com/artifactory/

- name:  Artifactory
  hosts: all
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: run-before,  period: daily  }
    - { role: artifactory, when: periodic }
    - { role: repo-load,   repo: "http://{{ common.net.localhost }}:{{ artifactory_port | default( artifactory.port ) }}/artifactory/repo/" }
    - run-after
