---
# Asgard playbook for Ubuntu
# https://github.com/Netflix/asgard

- name:  Asgard
  hosts: all
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml
    # So we don't fail when AWS credentials are provided using --extra-vars and "aws.yml" is missing
    - [ roles/asgard/vars/aws.yml, vars/common.yml ]

  roles:
    - { role: periodic-before, period: "{{ 24 * 3600 }}" }
    - { role: base, when: periodic }
    - java
    - asgard
    - periodic-after
