---
# Asgard playbook for Ubuntu
# https://github.com/Netflix/asgard

- name:  Asgard
  hosts: all
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml
    - [ bakery_payload.yml,        vars/common.yml ]
    - [ roles/asgard/vars/aws.yml, vars/common.yml ]

  roles:
    - { role: run-before, period: daily    }
    - { role: base,       when:   periodic }
    - { role: ansible,    when:   periodic }
    - { role: java,       when:   periodic }
    - asgard
    - run-after
