---
# Docker playbook for Ubuntu, auto-starting container specified on boot
# https://www.docker.com/

- name:  Docker
  hosts: all
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: run-before, period: daily }
    - { role: docker, start: evgenyg/echo, ports: [ 8080 ], wait: [{ path: / }], verify: [{ path: / }] }
    - run-after
