---
# Helios Master and Agent playbook for Ubuntu
# https://github.com/spotify/helios

- name:  Helios
  hosts: all
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: run-before, period: daily }
    - { role: docker, pull: [ evgenyg/echo ] }
    - helios
    - run-after
