---
# Helios Master and Agent playbook for Ubuntu
# https://github.com/spotify/helios

- name:  Helios
  hosts: helios
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: run-before, period: daily }
    # nginx image should be identical to that in roles/helios/vars/main.yml => helios.docker.nginx.image
    - { role: docker, when: periodic, pull: [ evgenyg/echo, 'nginx:1.7.9' ] }
    - helios
    - run-after
