---
# Helios Master playbook for Ubuntu
# https://github.com/spotify/helios

- name:  Helios Master
  hosts: all
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: run-before, period: daily  }
    - { role: base,       when: periodic }
    - { role: ansible,    when: periodic }
    - { role: java,       when: periodic, java_distribution: 'default-jdk' }
    - { role: zookeeper,  when: periodic, install_exhibitor: yes }
    - { role: golang,     when: periodic }
    - { role: skydns,     when: periodic }
    - { role: helios,     helios_role: master }
    - run-after
