---
# Helios Master playbook for Ubuntu
# https://github.com/spotify/helios

- name:  Helios Agent
  hosts: helios-agent*
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: run-before, period: daily }
    # nginx image should be identical to that in roles/helios/vars/main.yml => helios.docker.nginx.image
    - { role: docker, when: periodic, pull: [ 'nginx:1.7.9' ]}
    - { role: helios, helios_role: agent, use_consul: true }
    - run-after
