---
# Jenkins playbook for Ubuntu
# http://jenkins-ci.org/

- name:  Jenkins
  hosts: jenkins
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: run-before, period: daily }
    - { role: java,       java_distribution: oracle_jdk }
    - { role: docker,     when: periodic, pull: [ 'nginx:1.7.9', 'ubuntu:14.04.1', 'evgenyg/ansible:1.8.2' ]}
    - { role: helios,     when: periodic, helios_role: cli }
    - { role: jenkins,    jobs: [{ name: echo-service, repo: 'https://github.com/evgeny-goldin/echo-service.git' }]}
    - run-after
