---
- hosts: all
  sudo: yes
  vars_files:
    - vars.yml

  pre_tasks:
    - stat: path={{ touch_file }}
      register: touch
    - set_fact:
        once_a_day: "{{( not touch.stat.exists ) or (( ansible_date_time.epoch|int - touch.stat.atime|int ) > ( 3600 * 24 )) }}"
    - debug: var=once_a_day

  roles:
    - { role: base, when: once_a_day }
    - { role: npm,  when: once_a_day }
    - { role: java    }
    - { role: jenkins }

  tasks:
    - command: touch {{ touch_file }}
      when:    once_a_day
