---
# Jenkins playbook for Ubuntu
# http://jenkins-ci.org/

- name:  Jenkins
  hosts: all
  sudo:  yes

  roles:
    - { role: periodic-before, period: ( 24 * 3600 ) }
    - { role: base, when: periodic }
    - { role: npm,  when: periodic }
    - java
    - jenkins
    - periodic-after
