---
# Java, Groovy, Gradle, Scala playbook for Ubuntu

- name:  JVM
  hosts: jvm
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: run-before, period: daily }
    - groovy
    - gradle
    - maven
    - scala
    - run-after
