---
# Packer playbook for Ubuntu
# http://www.packer.io/

- name:  Packer
  hosts: all
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: run-before, period: daily    }
    - { role: base,       when:   periodic }
    - { role: ansible,    when:   periodic }
    - { role: docker,     when:   "( periodic|bool and ( not is_docker|bool ))" }
    - { role: vagrant,    when:   periodic }
    - { role: virtualbox, when:   periodic }
    - { role: ruby,       when:   periodic }
    - packer
    - run-after
