---
# TeamCity playbook for Ubuntu
# https://www.jetbrains.com/teamcity/

- name:  TeamCity
  hosts: teamcity
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: run-before, period: daily }
    - { role: maven,  when: periodic }
    - { role: gradle, when: periodic }
    - teamcity
    - run-after
