---
# https://zookeeper.apache.org/doc/r3.4.6/zookeeperAdmin.html#sc_zkMulitServerSetup
# https://zookeeper.apache.org/doc/r3.4.6/zookeeperAdmin.html#sc_configuration

- set_fact:
    my_id:            "{{ zk_instances | index( [ ansible_fqdn, ansible_hostname ] + ansible_all_ipv4_addresses + ansible_all_ipv6_addresses ) + 1 }}"
    zk_all_instances: "{{ zk_instances | transform2( 'lambda host, port: host + \":\" + port', zookeeper_port ) | join( ',' ) }}"
    all_ids:          "{{ range( 1, zk_instances|length + 1 ) | join(' ') }}" # '1 2 3' for 3 ZK instances

- debug:
    msg: "My ZK id is '{{ my_id }}' (of '{{ all_ids }}'), configuring cluster of {{ zk_instances|length }} ZK instances: {{ zk_all_instances }}"

- file:       dest="{{ zookeeper.my_id_file }}" state=absent
- lineinfile: dest="{{ zookeeper.my_id_file }}" line="{{ my_id }}" create=yes

- name: Updating ZK config
  lineinfile:
    dest: "{{ zookeeper_config }}"
    line: "server.{{ item.0|int + 1 }}={{ item.1 }}:2888:3888"
  with_indexed_items: zk_instances
