---
- set_fact:
    exhibitor_version: "{{ exhibitor.version | calculate( exhibitor.latest ) }}"
- set_fact:
    exhibitor_port:    "{{ exhibitor_port | default( exhibitor.port ) }}"
    exhibitor_jar:     "{{ exhibitor.home }}/build/libs/exhibitor-{{ exhibitor_version }}.jar"

- name: Stopping Exhibitor service
  service: name=exhibitor state=stopped
  ignore_errors: yes

- stat: path={{ exhibitor_jar }}
  register: exhibitor_jar_stat

- name: Cloning Gradle provider
  git:
    repo: "{{ exhibitor.gradle_provider }}"
    dest: "{{ exhibitor.home }}"
  when: ( not exhibitor_jar_stat.stat.exists | bool )

- name: Writing Exhibitor build file
  template:
    src:  exhibitor-build.gradle
    dest: "{{ exhibitor.home }}/build.gradle"
  when: ( not exhibitor_jar_stat.stat.exists | bool )

- name: Building Exhibitor standalone
  command: ./gradlew clean jar
  args:
    chdir: "{{ exhibitor.home }}"
  when: ( not exhibitor_jar_stat.stat.exists | bool )

- name:     Running Exhibitor standalone help
  command:  java -jar '{{ exhibitor_jar }}' --help
  register: exhibitor_help_out

- name:  Verifying Exhibitor standalone help
  assert:
    that:
      - "'Exhibitor v{{ exhibitor_version }}' in exhibitor_help_out.stdout"
      - "'Print this help'                    in exhibitor_help_out.stdout"
      - "'Default Property Names'             in exhibitor_help_out.stdout"

- name: Generating Exhibitor upstart script
  template:
    src:  exhibitor-upstart
    dest: "{{ ubuntu.init_dir }}/exhibitor.conf"

- name: Starting Exhibitor service
  service: name=exhibitor state=started enabled=yes

- name: Verifying Exhibitor endpoint
  wait_for: port={{ exhibitor_port }} timeout=10

- name: Verifying Exhibitor HTTP endpoint
  uri:  url="http://{{ common.net.localhost }}:{{ exhibitor_port }}/exhibitor/v1/ui/index.html" return_content=yes
  register: exhibitor_out

- name: Verifying Exhibitor HTTP endpoint
  assert:
    that:
      - "'Exhibitor for ZooKeeper' in exhibitor_out.content"
      - "'Control Panel'           in exhibitor_out.content"
      - "'Backup and Restore'      in exhibitor_out.content"
