---
- name: Calculating Exhibitor version
  set_fact:
    exhibitor_version: "{{ exhibitor.version | calculate( exhibitor.latest ) }}"
- set_fact:
    exhibitor_port:    "{{ exhibitor_port | default( exhibitor.port ) }}"
    exhibitor_jar:     "{{ exhibitor.home }}/build/libs/exhibitor-{{ exhibitor_version }}.jar"

- stat: path={{ exhibitor_jar }}
  register: exhibitor_jar_stat

- set_fact:
    exhibitor_jar_available: exhibitor_jar_stat.stat.exists | bool

- name: Cloning Gradle provider
  git:
    repo: "{{ exhibitor.gradle_provider }}"
    dest: "{{ exhibitor.home }}"
  when: not exhibitor_jar_available

- name: Writing Exhibitor build file
  template:
    src:  exhibitor-build.gradle
    dest: "{{ exhibitor.home }}/build.gradle"
  when: not exhibitor_jar_available

- name: Building Exhibitor standalone
  command: ./gradlew clean jar
  args:
    chdir: "{{ exhibitor.home }}"
  when: not exhibitor_jar_available

- name:     Running Exhibitor standalone help
  command:  java -jar '{{ exhibitor_jar }}' --help
  register: exhibitor_help_out

- name:  Verifying Exhibitor standalone help
  assert:
    that:
      - "'Exhibitor v{{ exhibitor_version }}' in exhibitor_help_out.stdout"
      - "'Print this help'                    in exhibitor_help_out.stdout"
      - "'Default Property Names'             in exhibitor_help_out.stdout"

- include: "{{ common.utils.service }}"
  vars:
    title:   Exhibitor
    service: exhibitor
    command: "java -jar '{{ exhibitor_jar }}' -c file --port {{ exhibitor_port }}"
    port:    "{{ exhibitor_port }}"
    verify:
      - { status: 404 }
      - { path: /exhibitor, status: 404 }
      - { path: /exhibitor/v1/ui/, status: 405 }
      - { path: /exhibitor/v1/ui/index.html, content: Exhibitor for ZooKeeper }
