---
- set_fact:
    zookeeper_home:   "{{ zookeeper.home }}/zookeeper-{{ zookeeper.version }}"
- set_fact:
    zookeeper_port:   "{{ zookeeper_port | default( zookeeper.port ) }}"
    zookeeper_server: "{{ zookeeper_home }}/bin/zkServer.sh"
    zookeeper_config: "{{ zookeeper_home }}/conf/zoo.cfg"

- name: Stopping ZooKeeper service
  service: name=zookeeper state=stopped
  ignore_errors: yes

- include: "{{ common.utils.download }}"
  vars:
    name:    ZooKeeper
    url:     "{{ zookeeper.url     | tokens( zookeeper ) }}"
    archive: "{{ zookeeper.archive | tokens( zookeeper ) }}"
    home:    "{{ zookeeper.home }}"

- include: "{{ common.utils.mkdir }}"
  vars:
    file:  "{{ zookeeper_config }}"

- name: Generating ZooKeeper config
  template:
    src:  zookeeper-config
    dest: "{{ zookeeper_config }}"

- name: Generating ZooKeeper upstart script
  template:
    src:  zookeeper-upstart
    dest: "{{ ubuntu.init_dir }}/zookeeper.conf"

- name:    Starting ZooKeeper service
  service: name=zookeeper state=started enabled=yes

- name: Verifying ZooKeeper endpoint
  wait_for: port={{ zookeeper_port }} timeout=3

- name: Running zkCli
  shell:    "echo 'ls /' | {{ zookeeper_home }}/bin/zkCli.sh -server {{ common.net.localhost }}:{{ zookeeper_port }}"
  register: zk_out

- name: Verifying zkCli
  fail: msg="Failed to execute zkCli - {{ zk_out }}"
  when: "'{{ common.net.localhost }}:{{ zookeeper_port }}(CONNECTED)' not in zk_out.stdout"
