---
- debug: var=helios_master
- debug: var=helios_master_port
- debug: var=zookeeper_port
- debug: var=registrar_port
- debug: var=domain

- set_fact:
    registrar_plugin:   "{{ helios.agent.registrar_plugin.jar | tokens( helios.agent.registrar_plugin ) }}"
    registrar_endpoint: "http://{{ helios_master }}:{{ registrar_port }}"

- include: verify-master.yml

- name: Downloading registrar plugin
  get_url:
    url:  "{{ helios.agent.registrar_plugin.url | tokens( helios.agent.registrar_plugin ) }}"
    dest: "{{ registrar_plugin }}"

- name: Creating Helios agent config directories
  command: mkdir -p $(dirname '{{ item }}')
  with_items:
    - "{{ helios.agent.config }}"
    - "{{ helios.agent.config_endpoints }}"

- name: Copying Helios agent configs
  template:
    src:  "{{ item.from }}"
    dest: "{{ item.to   }}"
  with_items:
    - { from: 'agent-config',           to: "{{ helios.agent.config }}" }
    - { from: 'agent-config-endpoints', to: "{{ helios.agent.config_endpoints }}" }

- name: Installing Helios agent
  apt:  deb="{{ helios.home }}/helios-agent_{{ helios_version }}_all.deb"

- name: Restarting Helios agent service
  service: name=helios-agent state=restarted enabled=yes
