---
- debug: var=helios_master
- debug: var=zookeeper_port
    
- name: Installing ZooKeeper client
  pip:  name=zk-shell
  
- set_fact: zk_host="{{ helios_master }}:{{ zookeeper_port }}"
- set_fact: zk_shell_command="zk-shell '{{ zk_host }}' --run-once 'ls /status/masters'" 
  
- name: Checking ZooKeeper service
  wait_for: host={{ helios_master }} port={{ zookeeper_port }} timeout=3

- name:     Running ZooKeeper client
  command:  "{{ zk_shell_command }}"
  register: zk_shell_out
- debug:    msg="{{ zk_shell_command }} => '{{ zk_shell_out.stdout }}'"
  
- name:  Verifying ZooKeeper client was able to connect
  assert:
    that:
      - not ( 'failed'        in zk_shell_out.stdout.lower())
      - not ( 'time-out'      in zk_shell_out.stdout.lower())
      - not ( 'not connected' in zk_shell_out.stdout.lower())
      - "'{{ helios_master | bare }}' in zk_shell_out.stdout"

- name: Copying Helios agent config
  template:
    src:  helios-agent
    dest: "{{ helios.agent.config }}"

- name: Downloading Helios SkyDNS plugin
  get_url:
    url:  "{{ helios.agent.sky_dns.url }}"
    dest: "{{ helios.agent.sky_dns.jar }}"

- name: Installing Helios agent
  apt:  deb="{{ helios.packages }}/helios-agent_{{ helios_version }}_all.deb"

- name: Restarting Helios agent service
  service: name=helios-agent state=restarted enabled=yes
