---
- name: Copying Helios agent config
  template:
    src:  helios-agent
    dest: "{{ helios.agent.config }}"

- name: Downloading Helios SkyDNS plugin
  get_url:
    url:  "{{ helios.agent.sky_dns.url }}"
    dest: "{{ helios.agent.sky_dns.jar }}"

- name: Installing Helios agent
  apt:  deb="{{ helios.packages }}/helios-agent_{{ helios_version }}_all.deb"

- name: Starting Helios agent service
  service: name=helios-agent state=started enabled=yes
