---
- name: Copying Helios agent config
  copy:
    src:  helios-agent
    dest: "{{ helios.agent.config }}"

- name: Installing Helios agent
  apt:  deb="{{ helios.helios_packages }}/helios-agent_{{ helios_version }}_all.deb"

- name: Starting Helios agent service
  service: name=helios-agent state=started enabled=yes
