---
- debug: var=helios_master
- debug: var=helios_master_port
- debug: var=zookeeper_port
- debug: var=registry_port
- debug: var=domain

- name: Creating Helios home directory
  file: path={{ helios.agent.home }} state=directory

- set_fact:
    registrar_plugin_jar: "{{ helios.agent.registrar_plugin.jar | tokens( helios.agent.registrar_plugin ) }}"

- name: Verifying Helios master endpoints
  wait_for: host={{ helios_master }} port={{ item }} timeout=3
  with_items:
    - "{{ helios_master_port }}"
    - "{{ zookeeper_port }}"
    - "{{ registry_port }}"

- name: Verifying Helios master HTTP endpoints
  uri:  url=http://{{ helios_master }}:{{ item.port }} status_code={{ item.status }}
  with_items:
    - { port: "{{ helios_master_port }}", status: 404 }

- name: Copying Helios agent configs
  template:
    src:  "{{ item.from }}"
    dest: "{{ item.to   }}"
  with_items:
    - { from: 'agent-config',  to: "{{ helios.agent.config }}" }
    - { from: 'helios-config', to: "{{ helios.agent.home }}/config" }

- name: Downloading registrar plugin
  get_url:
    url:  "{{ helios.agent.registrar_plugin.url | tokens( helios.agent.registrar_plugin ) }}"
    dest: "{{ registrar_plugin_jar }}"

- name: Installing Helios agent
  apt:  deb="{{ helios.home }}/helios-agent_{{ helios_version }}_all.deb"

- name: Restarting Helios agent service
  service: name=helios-agent state=restarted enabled=yes

- name:     Running Helios master dig
  command:  dig @{{ helios_master }}
  register: dig_out

- name: Verifying Helios master dig
  assert:
    that:
      - "'Got answer'       in dig_out.stdout"
      - "'QUESTION SECTION' in dig_out.stdout"
      - "'Query time'       in dig_out.stdout"
