---
- debug: var=helios_master
- debug: var=helios_master_port
- debug: var=zookeeper_port
- debug: var=registry_port
- debug: var=domain

- file: path={{ helios.agent.home }} state=directory
  
- name: Checking Helios master endpoints
  wait_for: host={{ helios_master }} port={{ item }} timeout=3
  with_items:
    - "{{ helios_master_port }}"
    - "{{ zookeeper_port }}"

- name: Checking Helios master HTTP endpoints
  uri:  url=http://{{ helios_master }}:{{ item.port }} status_code={{ item.status }}
  with_items:
    - { port: "{{ helios_master_port }}", status: 404 }

- name: Copying Helios agent configs
  template:
    src:  "{{ item.from }}"
    dest: "{{ item.to   }}"
  with_items:
    - { from: 'helios-agent',  to: "{{ helios.agent.config }}" }
    - { from: 'helios-config', to: "{{ helios.agent.home }}/config" }

- name: Downloading Helios SkyDNS plugin
  get_url:
    url:  "{{ helios.agent.sky_dns.url }}"
    dest: "{{ helios.agent.sky_dns.jar }}"

- name: Installing Helios agent
  apt:  deb="{{ helios.packages }}/helios-agent_{{ helios_version }}_all.deb"

- name: Restarting Helios agent service
  service: name=helios-agent state=restarted enabled=yes
