---
- include: zookeeper.yml

- include: exhibitor.yml

- name: Copying Helios master config
  copy:
    src:  helios-master
    dest: /etc/default/helios-master

- name: Installing Helios master
  apt:  deb="{{ helios.helios_packages }}/helios-master_{{ helios_version }}_all.deb"

- name: Starting Helios master service
  service: name=helios-master state=started enabled=yes
