---

- name: Checking for existence of a periodic 'touch' file
  stat: path={{ periodic_touch_file }}
  register: touch

- name: Calculating seconds since last periodic run
  set_fact:
    seconds_since_last_periodic: "{{ ansible_date_time.epoch|int - touch.stat.ctime|default(0)|int }}"

- debug: var=period

- name: Calculating if this should be a periodic run
  set_fact:
    periodic: "{{ ( not touch.stat.exists ) or ( seconds_since_last_periodic|int >= period|int ) }}"

- debug: var=periodic
- debug: var=common.start_service
- debug: var=ami

- name: Calculating 'start_service' flag
  set_fact:
    start_service: "{{ ( common.start_service|bool ) and ( not ( ami|default(false)|bool )) }}"

- debug: var=start_service

- debug: msg="Last successful periodic run was on {{ touch.stat.ctime | strftime }}, {{ seconds_since_last_periodic | explain }} ago"
  when: touch.stat.exists

- debug: msg="Next periodic run - now!"
  when: periodic

- debug: msg="Next periodic run will be on {{ ( touch.stat.ctime|int + period|int ) | strftime }}, in {{ ( period|int - seconds_since_last_periodic|int ) | explain }}"
  when: ( touch.stat.exists and ( not periodic|bool ))

# http://stackoverflow.com/questions/20010199/determining-if-a-process-runs-inside-lxc-docker
- name:     Checking if we're running inside Docker container
  shell:    grep docker /proc/1/cgroup | wc -l
  register: grep_result

- set_fact:
    is_docker: "{{ grep_result.stdout|int > 0 }}"

- debug: var=is_docker
