---
- set_fact:
    etcd_dir: "{{ etcd.dir_name | tokens( etcd ) }}"
- set_fact:
    etcd_bin: "{{ etcd.home }}/{{ etcd_dir }}/etcd"

- include: "{{ common.utils.service }}"
  vars:
    title:   Etcd
    service: etcd
    url:     "{{ etcd.url     | tokens({ 'dir_name': etcd_dir, 'version': etcd.version }) }}"
    archive: "{{ etcd.archive | tokens( etcd ) }}"
    home:    "{{ etcd.home }}"
    env:
      # https://github.com/coreos/etcd/blob/master/Documentation/configuration.md
      ETCD_ADDR:      "{{ common.net.local_ip }}:{{ etcd.port }}"
      ETCD_BIND_ADDR: "{{ common.net.any_ip }}:{{ etcd.port }}"
    tests:
      - { run: "{{ etcd_bin }} --version", expect: "{{ etcd.version }}" }
    command:   "{{ etcd_bin }} $ETCD_OPTS"
    port:      "{{ etcd.port }}"
    verify:
      - { path: /version,         content: '"releaseVersion":"{{ etcd.version }}"' }
      - { path: /v2/stats/leader, content: '{"leader":"' }
